// English Learning Content Structure
// Comprehensive English learning paths for competitive exams, international tests, and real-world usage

export type EnglishLevel = "beginner" | "intermediate" | "advanced";
export type EnglishGoal = "competitive-exam" | "ielts-toefl" | "foundation" | "real-world";

export interface EnglishTopic {
  id: string;
  name: string;
  description: string;
  icon: string;
  level: EnglishLevel;
  category: EnglishGoal;
  subtopics: string[];
  estimatedTime: number; // minutes
  questionCount: number;
}

export interface EnglishPath {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  goal: EnglishGoal;
  topics: EnglishTopic[];
  totalQuestions: number;
  estimatedWeeks: number;
}

// English Learning Paths
export const englishPaths: EnglishPath[] = [
  {
    id: "competitive-exam",
    name: "Competitive Exam English",
    description: "Master English for SSC, Banking, UPSC, and Railway exams",
    icon: "🎯",
    color: "#3B82F6",
    goal: "competitive-exam",
    totalQuestions: 500,
    estimatedWeeks: 8,
    topics: [
      {
        id: "grammar-basics",
        name: "Grammar Fundamentals",
        description: "Tenses, Articles, Prepositions, Voice, Narration",
        icon: "📝",
        level: "beginner",
        category: "competitive-exam",
        subtopics: [
          "Present Tenses",
          "Past Tenses",
          "Future Tenses",
          "Articles (a, an, the)",
          "Prepositions",
          "Active & Passive Voice",
          "Direct & Indirect Speech",
        ],
        estimatedTime: 120,
        questionCount: 100,
      },
      {
        id: "vocabulary-ssc",
        name: "Vocabulary for SSC/Banking",
        description: "Synonyms, Antonyms, One-word substitution, Idioms",
        icon: "📚",
        level: "intermediate",
        category: "competitive-exam",
        subtopics: [
          "Synonyms & Antonyms",
          "One Word Substitution",
          "Idioms & Phrases",
          "Spelling Correction",
          "Word Meanings",
        ],
        estimatedTime: 90,
        questionCount: 80,
      },
      {
        id: "sentence-improvement",
        name: "Sentence Improvement",
        description: "Error spotting, Fill in the blanks, Sentence rearrangement",
        icon: "✍️",
        level: "intermediate",
        category: "competitive-exam",
        subtopics: [
          "Error Spotting",
          "Fill in the Blanks",
          "Sentence Rearrangement",
          "Para Jumbles",
          "Sentence Completion",
        ],
        estimatedTime: 80,
        questionCount: 70,
      },
      {
        id: "comprehension",
        name: "Reading Comprehension",
        description: "Passage reading, inference, theme identification",
        icon: "📖",
        level: "advanced",
        category: "competitive-exam",
        subtopics: [
          "Short Passages",
          "Long Passages",
          "Main Theme",
          "Inference Questions",
          "Vocabulary in Context",
        ],
        estimatedTime: 100,
        questionCount: 50,
      },
      {
        id: "cloze-test",
        name: "Cloze Test",
        description: "Fill blanks in passages, context-based learning",
        icon: "🔤",
        level: "advanced",
        category: "competitive-exam",
        subtopics: [
          "Grammar-based Cloze",
          "Vocabulary-based Cloze",
          "Mixed Cloze Tests",
        ],
        estimatedTime: 60,
        questionCount: 40,
      },
    ],
  },
  {
    id: "ielts-toefl",
    name: "IELTS & TOEFL Preparation",
    description: "Complete preparation for international English tests",
    icon: "🌍",
    color: "#8B5CF6",
    goal: "ielts-toefl",
    totalQuestions: 600,
    estimatedWeeks: 12,
    topics: [
      {
        id: "ielts-reading",
        name: "IELTS Reading",
        description: "Academic passages, True/False/Not Given, Matching headings",
        icon: "📰",
        level: "advanced",
        category: "ielts-toefl",
        subtopics: [
          "Multiple Choice",
          "True/False/Not Given",
          "Matching Headings",
          "Matching Information",
          "Sentence Completion",
          "Summary Completion",
        ],
        estimatedTime: 150,
        questionCount: 120,
      },
      {
        id: "ielts-writing",
        name: "IELTS Writing",
        description: "Task 1 (Data description) and Task 2 (Essay writing)",
        icon: "✏️",
        level: "advanced",
        category: "ielts-toefl",
        subtopics: [
          "Task 1: Line Graphs",
          "Task 1: Bar Charts",
          "Task 1: Pie Charts",
          "Task 1: Tables",
          "Task 2: Opinion Essays",
          "Task 2: Discussion Essays",
          "Task 2: Problem-Solution Essays",
        ],
        estimatedTime: 120,
        questionCount: 50,
      },
      {
        id: "ielts-listening",
        name: "IELTS Listening",
        description: "British, Australian accents, Form filling, Note completion",
        icon: "🎧",
        level: "intermediate",
        category: "ielts-toefl",
        subtopics: [
          "Form Filling",
          "Note Completion",
          "Multiple Choice",
          "Matching",
          "Map/Diagram Labeling",
        ],
        estimatedTime: 100,
        questionCount: 80,
      },
      {
        id: "ielts-speaking",
        name: "IELTS Speaking",
        description: "Part 1 (Introduction), Part 2 (Cue card), Part 3 (Discussion)",
        icon: "🎤",
        level: "advanced",
        category: "ielts-toefl",
        subtopics: [
          "Part 1: Personal Questions",
          "Part 2: Cue Card Topics",
          "Part 3: Abstract Discussion",
          "Pronunciation Practice",
          "Fluency Training",
        ],
        estimatedTime: 90,
        questionCount: 60,
      },
      {
        id: "toefl-integrated",
        name: "TOEFL Integrated Tasks",
        description: "Reading + Listening combined tasks",
        icon: "🔗",
        level: "advanced",
        category: "ielts-toefl",
        subtopics: [
          "Integrated Writing",
          "Integrated Speaking",
          "Academic Discussions",
          "Email Writing",
        ],
        estimatedTime: 100,
        questionCount: 50,
      },
      {
        id: "academic-vocabulary",
        name: "Academic Vocabulary",
        description: "3000+ essential academic words for IELTS/TOEFL",
        icon: "🎓",
        level: "intermediate",
        category: "ielts-toefl",
        subtopics: [
          "Academic Word List",
          "Subject-specific Terms",
          "Collocations",
          "Formal vs Informal",
        ],
        estimatedTime: 150,
        questionCount: 240,
      },
    ],
  },
  {
    id: "foundation",
    name: "Foundation Builder - Complete Institute Course",
    description: "Professional English from A1 to B1 - 8 modules matching British Council curriculum",
    icon: "🏗️",
    color: "#10B981",
    goal: "foundation",
    totalQuestions: 4330,
    estimatedWeeks: 24,
    topics: [
      // MODULE 1: Alphabet & Phonics (A1 Beginner)
      {
        id: "alphabet-basics",
        name: "English Alphabet",
        description: "Capital letters, small letters, alphabetical order (A1)",
        icon: "🔤",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Capital Letters A-Z",
          "Small Letters a-z",
          "Letter Names vs Sounds",
          "Alphabetical Order",
          "Letter Recognition",
        ],
        estimatedTime: 60,
        questionCount: 50,
      },
      {
        id: "phonics-vowels",
        name: "Vowels & Consonants",
        description: "5 vowels, short/long sounds, consonant blends (A1)",
        icon: "🗣️",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "5 Vowels (a,e,i,o,u)",
          "Short Vowel Sounds",
          "Long Vowel Sounds",
          "Consonant Sounds",
          "Silent Letters",
        ],
        estimatedTime: 90,
        questionCount: 80,
      },
      {
        id: "pronunciation",
        name: "Pronunciation Fundamentals",
        description: "Mouth positions, word stress, minimal pairs (A1)",
        icon: "👄",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Voiced vs Voiceless",
          "Minimal Pairs",
          "Word Stress",
          "Indian Pronunciation Fixes",
        ],
        estimatedTime: 120,
        questionCount: 100,
      },

      // MODULE 2: Basic Grammar (A1)
      {
        id: "parts-of-speech",
        name: "8 Parts of Speech",
        description: "Noun, Pronoun, Verb, Adjective, Adverb, Preposition, Conjunction, Interjection (A1)",
        icon: "📝",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Nouns", "Pronouns", "Verbs", "Adjectives",
          "Adverbs", "Prepositions", "Conjunctions", "Interjections",
        ],
        estimatedTime: 120,
        questionCount: 150,
      },
      {
        id: "nouns-detailed",
        name: "Nouns Mastery",
        description: "Proper/common, singular/plural, countable/uncountable (A1)",
        icon: "🏷️",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Proper vs Common Nouns",
          "Singular → Plural",
          "Irregular Plurals",
          "Countable vs Uncountable",
          "Collective Nouns",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },
      {
        id: "pronouns-detailed",
        name: "Pronouns Complete",
        description: "Subject, object, possessive, reflexive, demonstrative (A1)",
        icon: "👤",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Subject Pronouns",
          "Object Pronouns",
          "Possessive Pronouns",
          "Reflexive Pronouns",
          "Demonstrative Pronouns",
        ],
        estimatedTime: 90,
        questionCount: 100,
      },
      {
        id: "articles",
        name: "Articles (a, an, the)",
        description: "Indefinite vs definite articles, usage rules (A1)",
        icon: "📌",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "'a' before consonant sounds",
          "'an' before vowel sounds",
          "'the' for specific things",
          "Zero Article",
        ],
        estimatedTime: 70,
        questionCount: 80,
      },
      {
        id: "adjectives",
        name: "Adjectives & Comparisons",
        description: "Types, order, degrees (positive, comparative, superlative) (A1)",
        icon: "⭐",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Types of Adjectives",
          "Order of Adjectives",
          "Degrees of Comparison",
          "Irregular Comparisons",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
      {
        id: "verbs-basics",
        name: "Verbs - Action Words",
        description: "Action, linking, helping, modal verbs, V1/V2/V3 forms (A1)",
        icon: "⚡",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Action Verbs",
          "Linking Verbs",
          "Helping Verbs",
          "Modal Verbs",
          "Verb Forms (V1,V2,V3)",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },

      // MODULE 3: Tenses Mastery (A1-A2) - Most Important
      {
        id: "present-simple",
        name: "Present Simple Tense",
        description: "Daily routines, habits, facts (I play, He plays) (A1)",
        icon: "☀️",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "Basic Structure",
          "Adding -s/-es",
          "Negative Form",
          "Questions",
          "Time Expressions",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "present-continuous",
        name: "Present Continuous Tense",
        description: "Actions happening now (I am studying) (A1)",
        icon: "▶️",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "am/is/are + V-ing",
          "Adding -ing",
          "Negative & Questions",
          "Stative Verbs",
          "Simple vs Continuous",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "present-perfect",
        name: "Present Perfect Tense",
        description: "Past actions with present relevance (I have finished) (A2)",
        icon: "✅",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "has/have + V3",
          "Regular & Irregular V3",
          "ever, never, already, yet",
          "since vs for",
          "Perfect vs Simple Past",
        ],
        estimatedTime: 120,
        questionCount: 120,
      },
      {
        id: "past-simple",
        name: "Past Simple Tense",
        description: "Completed past actions (I went, She studied) (A1)",
        icon: "⏪",
        level: "beginner",
        category: "foundation",
        subtopics: [
          "V2 Form",
          "Regular Verbs -ed",
          "Irregular Verbs",
          "Negative & Questions",
          "Time Expressions",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "past-continuous",
        name: "Past Continuous Tense",
        description: "Action in progress in the past (I was studying) (A2)",
        icon: "🔄",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "was/were + V-ing",
          "Two simultaneous actions",
          "Interrupted actions",
          "while vs when",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "future-simple",
        name: "Future Simple Tense",
        description: "Future predictions, promises (I will help) (A2)",
        icon: "⏩",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "will + V1",
          "Negative & Questions",
          "will vs be going to",
          "Future Time Expressions",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "tenses-advanced",
        name: "Advanced Tenses & Comparison",
        description: "Future Continuous, Perfect Continuous, all tense comparison (A2-B1)",
        icon: "⏰",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Future Continuous",
          "Present Perfect Continuous",
          "Past Perfect",
          "Tense Timeline",
          "Mixed Practice",
        ],
        estimatedTime: 150,
        questionCount: 510,
      },

      // MODULE 4: Sentence Construction (A2-B1)
      {
        id: "sentence-types",
        name: "Types of Sentences",
        description: "Simple, compound, complex sentences (A2)",
        icon: "📐",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Simple Sentences",
          "Compound Sentences",
          "Complex Sentences",
          "Using Conjunctions",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
      {
        id: "subject-verb-agreement",
        name: "Subject-Verb Agreement",
        description: "Singular/plural agreement, tricky cases (A2)",
        icon: "🔗",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Singular → Singular Verb",
          "Plural → Plural Verb",
          "Compound Subjects",
          "Tricky Cases",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
      {
        id: "active-passive",
        name: "Active & Passive Voice",
        description: "Voice conversion, passive in all tenses (B1)",
        icon: "🔀",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Active Voice",
          "Passive Voice",
          "Voice in All Tenses",
          "When to Use Passive",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },
      {
        id: "reported-speech",
        name: "Direct & Indirect Speech",
        description: "Reporting statements, questions, commands (B1)",
        icon: "💬",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Direct → Indirect",
          "Tense Changes",
          "Pronoun Changes",
          "Reporting Questions",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },

      // MODULE 5: Vocabulary Building (A2-B1)
      {
        id: "essential-vocabulary",
        name: "Essential 1000 Words",
        description: "Most common English words for daily use (A2)",
        icon: "💬",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "200 Common Nouns",
          "200 Common Verbs",
          "200 Common Adjectives",
          "Time & Place Words",
        ],
        estimatedTime: 150,
        questionCount: 250,
      },
      {
        id: "synonyms-antonyms",
        name: "Synonyms & Antonyms",
        description: "Words with similar and opposite meanings (A2)",
        icon: "🔄",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Common Synonyms",
          "Common Antonyms",
          "Context Usage",
        ],
        estimatedTime: 100,
        questionCount: 150,
      },
      {
        id: "word-formation",
        name: "Word Formation",
        description: "Prefixes, suffixes, compound words (B1)",
        icon: "🔧",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Prefixes (un-, re-, pre-)",
          "Suffixes (-ness, -tion, -ly)",
          "Compound Words",
          "Word Families",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
      {
        id: "phrasal-verbs",
        name: "Phrasal Verbs",
        description: "100 most common phrasal verbs (B1)",
        icon: "🚀",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "get, take, put",
          "look, go, come",
          "Separable vs Inseparable",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },
      {
        id: "idioms",
        name: "Idioms & Proverbs",
        description: "Common English idioms and proverbs (B1)",
        icon: "🎭",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "100 Common Idioms",
          "50 Proverbs",
          "Figurative Language",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },

      // MODULE 6: Reading Skills (A2-B1)
      {
        id: "reading-fundamentals",
        name: "Reading Fundamentals",
        description: "Skimming, scanning, context clues (A2)",
        icon: "📖",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Skimming for Main Idea",
          "Scanning for Info",
          "Context Clues",
          "Reading Speed",
        ],
        estimatedTime: 60,
        questionCount: 80,
      },
      {
        id: "short-stories",
        name: "Short Stories",
        description: "50-100 word simple stories (A2)",
        icon: "📕",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Story Comprehension",
          "Character & Plot",
          "Story Sequence",
          "Moral Lessons",
        ],
        estimatedTime: 90,
        questionCount: 120,
      },
      {
        id: "reading-comprehension",
        name: "Reading Comprehension",
        description: "Passages with questions (A2-B1)",
        icon: "📰",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Main Idea Questions",
          "Detail Questions",
          "Inference Questions",
          "Vocabulary in Context",
        ],
        estimatedTime: 100,
        questionCount: 150,
      },

      // MODULE 7: Writing Skills (A2-B1)
      {
        id: "writing-basics",
        name: "Writing Correct Sentences",
        description: "Capitalization, punctuation, complete sentences (A2)",
        icon: "✍️",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Capitalization Rules",
          "Punctuation Marks",
          "Complete Sentences",
          "Avoiding Run-ons",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
      {
        id: "paragraph-writing",
        name: "Paragraph Writing",
        description: "Topic sentence, supporting details, conclusion (A2)",
        icon: "📄",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Paragraph Structure",
          "Unity & Coherence",
          "Transition Words",
          "Types of Paragraphs",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },
      {
        id: "essay-writing",
        name: "Essay Writing Basics",
        description: "Introduction, body, conclusion (B1)",
        icon: "📝",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Essay Structure",
          "Introduction Techniques",
          "Body Paragraphs",
          "Conclusion Writing",
        ],
        estimatedTime: 120,
        questionCount: 150,
      },
      {
        id: "letter-writing",
        name: "Letter Writing",
        description: "Formal and informal letters (B1)",
        icon: "✉️",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Letter Format",
          "Formal Letters",
          "Informal Letters",
          "Email Writing",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },

      // MODULE 8: Speaking & Listening (A2-B1)
      {
        id: "daily-conversations",
        name: "Daily Conversations",
        description: "Greetings, shopping, directions, phone calls (A2)",
        icon: "💬",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Greetings & Introductions",
          "Shopping Dialogues",
          "Asking Directions",
          "Phone Conversations",
        ],
        estimatedTime: 100,
        questionCount: 120,
      },
      {
        id: "pronunciation-practice",
        name: "Pronunciation Practice",
        description: "Difficult sounds, word stress, intonation (A2-B1)",
        icon: "🗣️",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "v/w, th, r/l sounds",
          "Word Stress Patterns",
          "Sentence Intonation",
          "Connected Speech",
        ],
        estimatedTime: 100,
        questionCount: 100,
      },
      {
        id: "listening-skills",
        name: "Listening Skills",
        description: "Understanding native speakers, different accents (B1)",
        icon: "👂",
        level: "intermediate",
        category: "foundation",
        subtopics: [
          "Main Ideas",
          "Specific Information",
          "Different Accents",
          "Note-taking",
        ],
        estimatedTime: 80,
        questionCount: 100,
      },
    ],
  },
  {
    id: "real-world",
    name: "Real-World English",
    description: "Practical English for daily life and work",
    icon: "💼",
    color: "#F59E0B",
    goal: "real-world",
    totalQuestions: 300,
    estimatedWeeks: 4,
    topics: [
      {
        id: "job-interviews",
        name: "Job Interview English",
        description: "Common questions, professional responses, confidence building",
        icon: "👔",
        level: "intermediate",
        category: "real-world",
        subtopics: [
          "Tell Me About Yourself",
          "Strengths & Weaknesses",
          "Why Should We Hire You",
          "Behavioral Questions",
          "Technical Questions",
        ],
        estimatedTime: 60,
        questionCount: 50,
      },
      {
        id: "daily-conversations",
        name: "Daily Conversations",
        description: "Shopping, banking, doctor, travel scenarios",
        icon: "🛒",
        level: "beginner",
        category: "real-world",
        subtopics: [
          "Shopping & Bargaining",
          "Bank Transactions",
          "Doctor Appointments",
          "Restaurant Orders",
          "Travel & Directions",
        ],
        estimatedTime: 80,
        questionCount: 80,
      },
      {
        id: "email-writing",
        name: "Email Writing",
        description: "Formal and informal emails for work and personal use",
        icon: "📧",
        level: "intermediate",
        category: "real-world",
        subtopics: [
          "Formal Business Emails",
          "Informal Personal Emails",
          "Complaint Emails",
          "Request Emails",
          "Thank You Emails",
        ],
        estimatedTime: 70,
        questionCount: 60,
      },
      {
        id: "presentations",
        name: "Presentations & Public Speaking",
        description: "Deliver confident presentations in English",
        icon: "🎙️",
        level: "advanced",
        category: "real-world",
        subtopics: [
          "Opening & Closing",
          "Structuring Presentations",
          "Visual Aids",
          "Handling Questions",
          "Voice Modulation",
        ],
        estimatedTime: 50,
        questionCount: 40,
      },
      {
        id: "business-english",
        name: "Business English",
        description: "Professional communication, meetings, reports",
        icon: "💻",
        level: "advanced",
        category: "real-world",
        subtopics: [
          "Meeting Vocabulary",
          "Report Writing",
          "Negotiation Skills",
          "Phone Etiquette",
        ],
        estimatedTime: 60,
        questionCount: 70,
      },
    ],
  },
];

// Quick level assessment questions (3 questions to detect user level)
export const levelAssessmentQuestions = [
  {
    question: "Choose the correct sentence:",
    options: [
      "She don't like coffee",
      "She doesn't likes coffee",
      "She doesn't like coffee",
      "She not like coffee",
    ],
    correctAnswer: 2,
    level: "beginner",
  },
  {
    question: "What does 'ubiquitous' mean?",
    options: [
      "Very rare",
      "Present everywhere",
      "Extremely large",
      "Highly unusual",
    ],
    correctAnswer: 1,
    level: "intermediate",
  },
  {
    question: "Choose the best phrase to complete: 'Despite _____ extensively, the team failed to achieve the desired outcome.'",
    options: [
      "to prepare",
      "preparing",
      "prepared",
      "preparation",
    ],
    correctAnswer: 1,
    level: "advanced",
  },
];

// Helper functions
export function getPathById(pathId: string): EnglishPath | undefined {
  return englishPaths.find((p) => p.id === pathId);
}

export function getTopicById(pathId: string, topicId: string): EnglishTopic | undefined {
  const path = getPathById(pathId);
  return path?.topics.find((t) => t.id === topicId);
}

export function getAllTopics(): EnglishTopic[] {
  return englishPaths.flatMap((path) => path.topics);
}

export function getTopicsByLevel(level: EnglishLevel): EnglishTopic[] {
  return getAllTopics().filter((topic) => topic.level === level);
}

export function getTopicsByGoal(goal: EnglishGoal): EnglishTopic[] {
  return getAllTopics().filter((topic) => topic.category === goal);
}

// Get user level from assessment score
export function getUserLevelFromScore(score: number): EnglishLevel {
  if (score === 0) return "beginner";
  if (score === 1) return "beginner";
  if (score === 2) return "intermediate";
  if (score === 3) return "advanced";
  return "beginner";
}
