/**
 * REVISED FOUNDATION ENGLISH CURRICULUM
 * 33 comprehensive topics (merged from 77 granular topics)
 * British Council A1-B1 aligned, Indian learner focused
 */

export type EnglishLevel = "beginner" | "intermediate" | "advanced";
export type EnglishGoal = "foundation";

export interface EnglishTopic {
  id: string;
  name: string;
  description: string;
  icon: string;
  level: EnglishLevel;
  category: EnglishGoal;
  subtopics: string[];
  estimatedTime: number;
  questionCount: number;
}

export interface EnglishModule {
  id: string;
  name: string;
  description: string;
  icon: string;
  topics: EnglishTopic[];
}

export interface EnglishPath {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  goal: EnglishGoal;
  modules: EnglishModule[];
  totalQuestions: number;
  estimatedWeeks: number;
}

export const foundationPathRevised: EnglishPath = {
  id: "foundation",
  name: "Foundation Builder",
  description: "Complete English from A1 to B1 - Professional curriculum",
  icon: "🏗️",
  color: "#10B981",
  goal: "foundation",
  totalQuestions: 2000,
  estimatedWeeks: 20,
  modules: [
    // ========== MODULE 1: ALPHABET & PHONICS (3 topics) ==========
    {
      id: "module-1-alphabet",
      name: "Module 1: Alphabet & Phonics",
      description: "Master the building blocks of English",
      icon: "🔤",
      topics: [
        {
          id: "alphabet-basics",
          name: "English Alphabet",
          description: "26 letters, capital and small, letter sounds",
          icon: "🔤",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Capital Letters A-Z",
            "Small Letters a-z",
            "Letter Names vs Sounds",
            "Alphabetical Order",
            "Letter Recognition",
          ],
          estimatedTime: 60,
          questionCount: 50,
        },
        {
          id: "phonics-vowels",
          name: "Vowels & Consonants",
          description: "5 vowels and 21 consonants with sounds",
          icon: "🗣️",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Short Vowel Sounds (cat, bed, sit)",
            "Long Vowel Sounds (cake, meet, like)",
            "Consonant Sounds",
            "Vowel-Consonant Blends",
            "Silent Letters",
          ],
          estimatedTime: 90,
          questionCount: 80,
        },
        {
          id: "pronunciation-basics",
          name: "Pronunciation Fundamentals",
          description: "How to pronounce English sounds correctly",
          icon: "👄",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Mouth Positions for Sounds",
            "Voiced vs Voiceless Sounds",
            "Minimal Pairs (ship/sheep, bit/beat)",
            "Word Stress Basics",
            "Common Indian Pronunciation Mistakes",
          ],
          estimatedTime: 120,
          questionCount: 100,
        },
      ],
    },

    // ========== MODULE 2: BASIC GRAMMAR (6 topics) ==========
    {
      id: "module-2-grammar",
      name: "Module 2: Basic Grammar",
      description: "Essential grammar rules everyone must know",
      icon: "📝",
      topics: [
        {
          id: "parts-of-speech",
          name: "Parts of Speech",
          description: "8 types: Noun, Pronoun, Verb, Adjective, Adverb, Preposition, Conjunction, Interjection",
          icon: "🎯",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Nouns (Person, Place, Thing, Idea)",
            "Pronouns (I, you, he, she, it, we, they)",
            "Verbs (Action words)",
            "Adjectives (Describing words)",
            "Adverbs (How, when, where)",
            "Prepositions (in, on, at, by)",
            "Conjunctions (and, but, or)",
            "Interjections (Wow!, Oh!, Alas!)",
          ],
          estimatedTime: 180,
          questionCount: 150,
        },
        {
          id: "nouns-detailed",
          name: "Nouns Mastery",
          description: "Types, number, gender, case",
          icon: "📦",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Proper vs Common Nouns",
            "Collective Nouns (team, class, family)",
            "Abstract Nouns (happiness, love, anger)",
            "Material Nouns (gold, water, wood)",
            "Singular vs Plural",
            "Irregular Plurals (child→children, mouse→mice)",
            "Countable vs Uncountable Nouns",
            "Gender (masculine, feminine, neuter)",
          ],
          estimatedTime: 150,
          questionCount: 120,
        },
        {
          id: "pronouns-detailed",
          name: "Pronouns Complete",
          description: "Personal, possessive, reflexive, demonstrative",
          icon: "👤",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Subject Pronouns (I, you, he, she, it)",
            "Object Pronouns (me, you, him, her, it)",
            "Possessive Pronouns (my, your, his, her)",
            "Possessive Adjectives vs Pronouns",
            "Reflexive Pronouns (myself, yourself, himself)",
            "Demonstrative Pronouns (this, that, these, those)",
            "Interrogative Pronouns (who, what, which)",
            "Relative Pronouns (who, which, that)",
          ],
          estimatedTime: 120,
          questionCount: 100,
        },
        {
          id: "articles",
          name: "Articles (a, an, the)",
          description: "Definite and indefinite articles with rules",
          icon: "📰",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Indefinite Articles: A vs An",
            "When to use 'A' (before consonant sounds)",
            "When to use 'An' (before vowel sounds)",
            "Definite Article: The",
            "When to use 'The' (specific things)",
            "When NOT to use articles",
            "Zero Article (going to school, by car)",
            "Common Mistakes Indians Make",
          ],
          estimatedTime: 90,
          questionCount: 80,
        },
        {
          id: "adjectives",
          name: "Adjectives & Comparisons",
          description: "Describing words and degrees of comparison",
          icon: "🎨",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Types of Adjectives (quality, quantity, number)",
            "Order of Adjectives (opinion, size, age, color)",
            "Degrees of Comparison (positive, comparative, superlative)",
            "Comparative: -er, more (bigger, more beautiful)",
            "Superlative: -est, most (biggest, most beautiful)",
            "Irregular Comparisons (good→better→best)",
            "Adjectives vs Adverbs",
          ],
          estimatedTime: 120,
          questionCount: 100,
        },
        {
          id: "verbs-basics",
          name: "Verbs - Action Words",
          description: "Main verbs, helping verbs, modals, verb forms",
          icon: "⚡",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Action Verbs (run, eat, sleep, write)",
            "Linking Verbs (is, am, are, was, were)",
            "Helping Verbs (do, does, did, have, has, had)",
            "Modal Verbs (can, could, may, might, must, should)",
            "Transitive vs Intransitive Verbs",
            "Regular vs Irregular Verbs",
            "Verb Forms (V1, V2, V3, V4, V5)",
          ],
          estimatedTime: 150,
          questionCount: 120,
        },
      ],
    },

    // ========== MODULE 3: ESSENTIAL TENSES (8 topics - COMPREHENSIVE) ==========
    {
      id: "module-3-tenses",
      name: "Module 3: Essential Tenses",
      description: "All major tenses with affirmative, negative, and questions",
      icon: "⏰",
      topics: [
        {
          id: "present-simple-complete",
          name: "Present Simple Tense",
          description: "Daily routines, habits, facts (I play, He plays, I don't play, Do you play?)",
          icon: "☀️",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Affirmative: I/You/We/They + V1",
            "Third Person: He/She/It + V1+s/es",
            "Negative: don't/doesn't + V1",
            "Questions: Do/Does + Subject + V1?",
            "Time Expressions (always, usually, often, sometimes, never)",
            "Common Mistakes",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "present-continuous-complete",
          name: "Present Continuous Tense",
          description: "Actions happening now (I am studying, I'm not studying, Are you studying?)",
          icon: "▶️",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Affirmative: am/is/are + V-ing",
            "Negative: am not/isn't/aren't + V-ing",
            "Questions: Am/Is/Are + Subject + V-ing?",
            "Adding -ing Rules (play→playing, run→running, write→writing)",
            "Stative Verbs (know, love, hate, want)",
            "Present Simple vs Present Continuous",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "past-simple-complete",
          name: "Past Simple Tense",
          description: "Completed past actions (I went, I didn't go, Did you go?)",
          icon: "⏪",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Affirmative: Subject + V2",
            "Regular Verbs: -ed (played, studied, worked)",
            "Irregular Verbs: (go→went, see→saw, eat→ate)",
            "Negative: didn't + V1",
            "Questions: Did + Subject + V1?",
            "Time Expressions (yesterday, last week, ago)",
            "Common Mistakes",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "past-continuous-complete",
          name: "Past Continuous Tense",
          description: "Actions in progress in the past (I was studying when she called)",
          icon: "🔄",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Structure: was/were + V-ing",
            "Negative: wasn't/weren't + V-ing",
            "Questions: Was/Were + Subject + V-ing?",
            "Two Simultaneous Actions (While I was studying, she was cooking)",
            "Interrupted Actions (I was studying when she called)",
            "While vs When",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "future-tenses",
          name: "Future Tenses",
          description: "will, going to, and their differences",
          icon: "⏩",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Future Simple: will + V1",
            "Going To Future: am/is/are going to + V1",
            "Will vs Going To (spontaneous vs planned)",
            "Negative: won't/not going to",
            "Questions: Will...? / Are you going to...?",
            "Time Expressions (tomorrow, next week, soon)",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "present-perfect-complete",
          name: "Present Perfect Tense",
          description: "Past actions with present relevance (I have finished, Have you eaten?)",
          icon: "✅",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Structure: has/have + V3",
            "Regular V3: -ed (finished, worked)",
            "Irregular V3: (go→gone, see→seen, eat→eaten)",
            "Negative: hasn't/haven't + V3",
            "Questions: Has/Have + Subject + V3?",
            "Time Markers: ever, never, already, yet, just, recently",
            "For vs Since (for 3 years, since 2020)",
            "Present Perfect vs Past Simple",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "past-perfect",
          name: "Past Perfect Tense",
          description: "Action completed before another past action (I had finished before she arrived)",
          icon: "⏮️",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Structure: had + V3",
            "Usage: Earlier past action",
            "With Past Simple (I had eaten when she called)",
            "Negative: hadn't + V3",
            "Questions: Had + Subject + V3?",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
        {
          id: "tense-comparison",
          name: "All Tenses Comparison",
          description: "When to use which tense - complete comparison",
          icon: "🔀",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Tense Timeline",
            "Present Tenses Comparison",
            "Past Tenses Comparison",
            "Future Tenses Comparison",
            "Perfect Tenses Comparison",
            "Mixed Tense Practice",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
      ],
    },

    // ========== MODULE 4: MODALS & VOICE (3 topics) ==========
    {
      id: "module-4-modals-voice",
      name: "Module 4: Modals & Voice",
      description: "Modal verbs and passive voice",
      icon: "🎭",
      topics: [
        {
          id: "modal-verbs",
          name: "Modal Verbs",
          description: "can, could, may, might, must, should, will, would",
          icon: "🔑",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Ability: can, could",
            "Permission: can, may",
            "Possibility: may, might, could",
            "Obligation: must, should",
            "Advice: should, ought to",
            "Requests: can, could, would",
            "Modal + have + V3 (past modals)",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "passive-voice",
          name: "Passive Voice",
          description: "Converting active to passive in all tenses",
          icon: "🔀",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Active vs Passive",
            "Basic Structure: is/am/are + V3",
            "Passive in Present Simple",
            "Passive in Past Simple",
            "Passive in Future Simple",
            "Passive in Present Perfect",
            "Passive with Modals",
            "When to Use Passive",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "active-passive-conversion",
          name: "Voice Conversion Practice",
          description: "Converting between active and passive voice",
          icon: "↔️",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Subject-Object Swap",
            "By-Agent Addition",
            "Tense Consistency",
            "Mixed Practice",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
      ],
    },

    // ========== MODULE 5: ADVANCED STRUCTURES (4 topics) ==========
    {
      id: "module-5-advanced",
      name: "Module 5: Advanced Structures",
      description: "Reported speech, conditionals, relative clauses",
      icon: "🎓",
      topics: [
        {
          id: "reported-speech",
          name: "Direct & Indirect Speech",
          description: "Reporting statements, questions, and commands",
          icon: "💬",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Direct → Indirect (Statements)",
            "Tense Changes (say/said, will→would, can→could)",
            "Pronoun Changes (I→he/she, my→his/her)",
            "Time/Place Changes (today→that day, here→there)",
            "Reporting Questions",
            "Reporting Commands",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "conditionals",
          name: "Conditionals",
          description: "Zero, First, Second, Third conditionals",
          icon: "🎲",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Zero Conditional: If + Present, Present (facts)",
            "First Conditional: If + Present, will (real future)",
            "Second Conditional: If + Past, would (unreal present)",
            "Third Conditional: If + Past Perfect, would have (unreal past)",
            "Mixed Conditionals",
            "Unless, As long as, Provided that",
          ],
          estimatedTime: 150,
          questionCount: 150,
        },
        {
          id: "relative-clauses",
          name: "Relative Clauses",
          description: "Defining and non-defining relative clauses",
          icon: "🔗",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Relative Pronouns: who, which, that, whose, where, when",
            "Defining Clauses (essential info, no commas)",
            "Non-defining Clauses (extra info, with commas)",
            "Omitting Relative Pronouns",
            "Subject vs Object Relative Clauses",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "sentence-types",
          name: "Sentence Types",
          description: "Simple, compound, and complex sentences",
          icon: "📐",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Simple Sentences (one clause)",
            "Compound Sentences (and, but, or, so)",
            "Complex Sentences (subordinate clauses)",
            "Sentence Combining",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
      ],
    },

    // ========== MODULE 6: CONNECTING IDEAS (2 topics) ==========
    {
      id: "module-6-connectors",
      name: "Module 6: Connecting Ideas",
      description: "Conjunctions and linking words",
      icon: "🔗",
      topics: [
        {
          id: "conjunctions-connectors",
          name: "Conjunctions & Connectors",
          description: "and, but, or, so, because, although, however",
          icon: "➕",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Coordinating: and, but, or, so",
            "Subordinating: because, although, if, when, while",
            "Contrast: but, however, although",
            "Cause-Effect: because, so, therefore",
            "Addition: and, also, moreover",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
        {
          id: "time-sequence",
          name: "Time Sequence Words",
          description: "first, then, next, finally, meanwhile",
          icon: "🔢",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Sequencing: first, then, next, finally",
            "Simultaneous: while, meanwhile, at the same time",
            "Before/After",
            "Story Telling",
          ],
          estimatedTime: 80,
          questionCount: 80,
        },
      ],
    },

    // ========== MODULE 7: VOCABULARY BUILDING (4 topics) ==========
    {
      id: "module-7-vocabulary",
      name: "Module 7: Vocabulary Building",
      description: "Essential words and expressions",
      icon: "📚",
      topics: [
        {
          id: "essential-vocabulary",
          name: "Essential 1000 Words",
          description: "Most common English words for daily use",
          icon: "💬",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "200 Common Nouns",
            "200 Common Verbs",
            "200 Common Adjectives",
            "Time & Place Words",
            "Daily Life Vocabulary",
          ],
          estimatedTime: 150,
          questionCount: 250,
        },
        {
          id: "synonyms-antonyms",
          name: "Synonyms & Antonyms",
          description: "Words with similar and opposite meanings",
          icon: "↔️",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Common Synonyms (happy = joyful = glad)",
            "Common Antonyms (happy ↔ sad)",
            "Context-based Usage",
            "Word Choice",
          ],
          estimatedTime: 100,
          questionCount: 150,
        },
        {
          id: "phrasal-verbs",
          name: "Common Phrasal Verbs",
          description: "100 most used phrasal verbs",
          icon: "🚀",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "get up, get on, get off",
            "look after, look for, look up",
            "give up, give in, give away",
            "take off, take on, take after",
            "Separable vs Inseparable",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "idioms-expressions",
          name: "Idioms & Expressions",
          description: "Common English idioms and phrases",
          icon: "🎭",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "100 Common Idioms",
            "Weather Idioms",
            "Body Idioms",
            "Animal Idioms",
            "Figurative Language",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
      ],
    },

    // ========== MODULE 8: PRACTICAL ENGLISH (3 topics) ==========
    {
      id: "module-8-practical",
      name: "Module 8: Practical English",
      description: "Real-world English usage",
      icon: "💼",
      topics: [
        {
          id: "common-mistakes",
          name: "Common Mistakes for Indian Learners",
          description: "Typical errors Indians make and how to fix them",
          icon: "⚠️",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Article Errors (a, an, the)",
            "Preposition Mistakes (in, on, at)",
            "Tense Confusion",
            "Word Order Problems",
            "False Friends (Hindi-English)",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
        {
          id: "speaking-basics",
          name: "Daily Conversations",
          description: "Greetings, shopping, directions, phone calls",
          icon: "💬",
          level: "beginner",
          category: "foundation",
          subtopics: [
            "Greetings & Introductions",
            "Shopping Dialogues",
            "Asking Directions",
            "Phone Conversations",
            "Restaurant Orders",
          ],
          estimatedTime: 100,
          questionCount: 100,
        },
        {
          id: "writing-basics",
          name: "Basic Writing Skills",
          description: "Sentences, paragraphs, emails",
          icon: "✍️",
          level: "intermediate",
          category: "foundation",
          subtopics: [
            "Capitalization & Punctuation",
            "Complete Sentences",
            "Paragraph Structure",
            "Informal Emails",
            "Formal Emails",
          ],
          estimatedTime: 120,
          questionCount: 120,
        },
      ],
    },
  ],
};
