// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.705Z

const gate_cs_data_structures_Trees: BankQuestion[] = [
  {
    question: "Height of a balanced BST with n nodes is:",
    options: [
      "O(n)",
      "O(log n)",
      "O(n log n)",
      "O(1)",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2022",
    sourceDetail: "GATE 2022 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Trees };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_data_structures_Graphs: BankQuestion[] = [
  {
    question: "BFS traversal uses which data structure?",
    options: [
      "Stack",
      "Queue",
      "Heap",
      "Array",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2021",
    sourceDetail: "GATE 2021 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Graphs };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_data_structures_Sorting: BankQuestion[] = [
  {
    question: "Average complexity of Merge Sort is:",
    options: [
      "O(n)",
      "O(log n)",
      "O(n log n)",
      "O(n²)",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  },
  {
    question: "Which sorting algorithms are stable?",
    options: [
      "Merge Sort",
      "Quick Sort",
      "Insertion Sort",
      "Selection Sort",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Sorting };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_operating_systems_Processes: BankQuestion[] = [
  {
    question: "Which scheduling algorithm may cause starvation?",
    options: [
      "Round Robin",
      "Priority Scheduling",
      "FCFS",
      "FIFO",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Processes };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_operating_systems_Memory: BankQuestion[] = [
  {
    question: "Which memory management scheme avoids external fragmentation?",
    options: [
      "Paging",
      "Segmentation",
      "Dynamic partitioning",
      "Contiguous allocation",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2021",
    sourceDetail: "GATE 2021 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Memory };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_dbms_SQL: BankQuestion[] = [
  {
    question: "Which SQL clause removes duplicate rows?",
    options: [
      "UNIQUE",
      "DISTINCT",
      "PRIMARY",
      "GROUP",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 DBMS (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_dbms_SQL };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_dbms_Normalization: BankQuestion[] = [
  {
    question: "BCNF is stricter version of:",
    options: [
      "1NF",
      "2NF",
      "3NF",
      "4NF",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 DBMS (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_dbms_Normalization };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_computer_networks_TCP: BankQuestion[] = [
  {
    question: "Which protocol provides reliable communication?",
    options: [
      "UDP",
      "IP",
      "TCP",
      "ICMP",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Computer Networks (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_computer_networks_TCP };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_computer_networks_Routing: BankQuestion[] = [
  {
    question: "Which algorithm is used in link state routing?",
    options: [
      "Prim",
      "Kruskal",
      "Dijkstra",
      "Bellman Ford",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2022",
    sourceDetail: "GATE 2022 Computer Networks (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_computer_networks_Routing };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_theory_of_computation_Automata: BankQuestion[] = [
  {
    question: "Regular languages are accepted by:",
    options: [
      "PDA",
      "DFA",
      "TM",
      "CFG",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Theory of Computation (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_theory_of_computation_Automata };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_theory_of_computation_Grammar: BankQuestion[] = [
  {
    question: "Which are context free grammars?",
    options: [
      "Regular grammar",
      "Type 2 grammar",
      "Type 3 grammar",
      "Type 0 grammar",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2016",
    sourceDetail: "GATE 2016 Theory of Computation (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_theory_of_computation_Grammar };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_signals_and_systems_Fourier: BankQuestion[] = [
  {
    question: "Fourier transform converts signal into:",
    options: [
      "Time domain",
      "Frequency domain",
      "Space domain",
      "Amplitude domain",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Signals and Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_signals_and_systems_Fourier };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_communication_Modulation: BankQuestion[] = [
  {
    question: "Which modulation has highest bandwidth efficiency?",
    options: [
      "AM",
      "FM",
      "QAM",
      "PCM",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 Communication (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_communication_Modulation };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_control_systems_Stability: BankQuestion[] = [
  {
    question: "Routh Hurwitz criterion determines:",
    options: [
      "Gain",
      "Stability",
      "Phase",
      "Amplitude",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 Control Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_control_systems_Stability };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_network_theory_Kirchhoff: BankQuestion[] = [
  {
    question: "KCL is based on conservation of:",
    options: [
      "Energy",
      "Charge",
      "Power",
      "Voltage",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Network Theory (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_network_theory_Kirchhoff };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.708Z

const gate_cs_analog_electronics_Diodes: BankQuestion[] = [
  {
    question: "Zener diode is used for:",
    options: [
      "Amplification",
      "Voltage regulation",
      "Switching",
      "Oscillation",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 Analog Electronics (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_analog_electronics_Diodes };

// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.708Z

const gate_cs_operating_systems_Deadlock: BankQuestion[] = [
  {
    question: "Deadlock prevention removes which condition?",
    options: [
      "Mutual exclusion",
      "Circular wait",
      "Hold and wait",
      "All",
    ],
    correctAnswer: 3,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2016",
    sourceDetail: "GATE 2016 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Deadlock };

