// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.263Z

const jee_main_jee_physics_Mechanics: BankQuestion[] = [
  {
    question: "A body of mass 5 kg is moving with a velocity of 10 m/s. The kinetic energy of the body is:",
    options: [
      "250 J",
      "500 J",
      "1000 J",
      "2500 J",
    ],
    correctAnswer: 0,
    explanation: "KE = ½mv² = ½ × 5 × (10)² = ½ × 5 × 100 = 250 J",
    difficulty: "easy",
    source: "verified",
    year: "JEE Main 2024",
    sourceDetail: "Shift 1",
  }
];

export { jee_main_jee_physics_Mechanics };

// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.263Z

const neet_ug_neet_chemistry_Environmental_Chemistry: BankQuestion[] = [
  {
    question: "Which of the following is NOT a greenhouse gas?",
    options: [
      "Carbon dioxide",
      "Methane",
      "Nitrogen",
      "Water vapor",
    ],
    correctAnswer: 2,
    explanation: "Nitrogen (N₂) is not a greenhouse gas. It makes up 78% of the atmosphere but does not trap heat. CO₂, CH₄, and H₂O are all greenhouse gases.",
    difficulty: "easy",
    source: "verified",
    year: "NEET 2024",
  }
];

export { neet_ug_neet_chemistry_Environmental_Chemistry };

// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.264Z

const upsc_cse_upsc_history_Modern_India: BankQuestion[] = [
  {
    question: "The Constitution of India was adopted on:",
    options: [
      "26th January 1950",
      "26th November 1949",
      "15th August 1947",
      "26th January 1949",
    ],
    correctAnswer: 1,
    explanation: "The Constitution was adopted by the Constituent Assembly on 26th November 1949 and came into effect on 26th January 1950 (Republic Day).",
    difficulty: "easy",
    source: "verified",
    year: "UPSC CSE 2023",
    sourceDetail: "Prelims Paper 1",
  }
];

export { upsc_cse_upsc_history_Modern_India };

// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.264Z

const ssc_cgl_ssc_quant_Percentage: BankQuestion[] = [
  {
    question: "If 20% of a number is 50, then 50% of that number is:",
    options: [
      "100",
      "125",
      "150",
      "200",
    ],
    correctAnswer: 1,
    explanation: "Let the number be x. 20% of x = 50 → 0.2x = 50 → x = 250. Now 50% of 250 = 0.5 × 250 = 125",
    difficulty: "medium",
    source: "verified",
    year: "SSC CGL 2024",
  }
];

export { ssc_cgl_ssc_quant_Percentage };

