// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:30:41.071Z

const ca_foundation_ca_accounts_Basic_Accounting: BankQuestion[] = [
  {
    question: "A company incurs a loss of Rs. 10,000 in the previous year and has paid an advance tax of Rs. 2,500 on account of this loss. What is the amount that needs to be paid by the company in cash towards its tax liability for the current year?",
    options: [
      "Rs. 7,500",
      "Rs. 10,000 - (Advance tax of Rs. 2,500)",
      "Since there is a loss, no amount needs to be paid in cash towards tax liability for the current year.",
      "Only the advance tax already paid will be adjusted against future profits",
    ],
    correctAnswer: 0,
    explanation: "Step-by-step explanation: The concept being tested here is the accounting treatment of losses and advance taxes. When a company incurs a loss, it can either write off the entire loss or carry over part of it to future years. In this case, since there's an advance tax paid on account of the previous year's loss, we need to adjust the amount that needs to be paid in cash towards tax liability for the current year. Option (b) incorrectly suggests a straightforward subtraction, ignoring the fact that only a portion of the loss can be claimed as an advance tax deduction. Option (c) is incorrect because even though there's a loss, the company still needs to pay its tax liability for the current year. Option (d) is also incorrect because it fails to account for the advance tax already paid on account of the previous year's loss. The correct answer is that no amount needs to be paid in cash towards tax liability for the current year, as the advance tax will be adjusted against future profits. This requires an understanding of the accounting treatment of losses and advance taxes, as well as the ability to apply it to a real-world scenario.",
    difficulty: "easy",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { ca_foundation_ca_accounts_Basic_Accounting };
