// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:30:20.310Z

const cds_cds_gk_Geography: BankQuestion[] = [
  {
    question: "What is the difference in elevation between the summit of Mount Everest and its base?",
    options: [
      "Approximately 8.8 km",
      "About 8.8 kilometers, but note that this value does not account for the gradual slope at the base",
      "Exactly 8.8 kilometers, as the base is a flat plateau and the summit's height remains constant regardless of one's vantage point",
      "Around 9 kilometers, taking into consideration the variation in elevation due to the mountain's shape",
    ],
    correctAnswer: 1,
    explanation: "Step-by-step explanation: To answer this question accurately, we must consider the topography of Mount Everest and how it affects our measurement. Option A states a difference of approximately 8.8 km; however, this value does not account for the gradual slope at the base of the mountain. This makes option B a more accurate choice as it acknowledges the variation in elevation. Option C is incorrect because it assumes that the summit's height remains constant regardless of one's vantage point, which contradicts the concept of perspective in geography. Finally, option D suggests a difference of around 9 kilometers, taking into consideration the mountain's shape; while this value may be closer to reality, it is still an overestimation due to the flatness of the base. Therefore, option B provides the most accurate response given the context of the question and fundamental principles of geography.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { cds_cds_gk_Geography };
