// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:58:41.761Z

const cds_cds_english_Grammar: BankQuestion[] = [
  {
    question: "Identify the correct form of the possessive adjective in the following sentence: 'The book ______ my friend.'",
    options: [
      "belongs to",
      "belong to",
      "my friend's",
      "my friends'",
    ],
    correctAnswer: 2,
    explanation: "In English grammar, possessive adjectives are used to show that something belongs to someone or something. In the given sentence, 'my friend' is a singular noun phrase, so the correct form of the possessive adjective is 'my friend's'. This is because the apostrophe in 'friend''s indicates possession. Option A ('belongs to') and option B ('belong to') are incorrect because they do not show possession. Option D ('my friends') is also incorrect because it shows plural possession, whereas the sentence refers to a singular noun phrase. Therefore, option C ('my friend''s) is the correct answer.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { cds_cds_english_Grammar };
