// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:30:10.179Z

const clat_clat_gk_Static_GK: BankQuestion[] = [
  {
    question: "What percentage of India's population lives in urban areas, as per the 2011 Census?",
    options: [
      "40%",
      "60%",
      "67.7%",
      "75%",
    ],
    correctAnswer: 2,
    explanation: "To calculate this percentage, we need to understand the concept of urban and rural population. According to the 2011 Census, India's urban population was approximately 361.9 million, while its total population was around 1.21 billion (1227 crores). The percentage of urban population can be calculated by dividing the urban population by the total population and multiplying by 100. So, (361.9 / 1227) * 100 = 29.5%, which is close to option c. Option a is incorrect because it underestimates the actual percentage. Option b overestimates it, as per the given data. Option d is also incorrect because it exceeds the actual value. Therefore, the correct answer is option c, which states that approximately 67.7% of India's population lives in urban areas.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { clat_clat_gk_Static_GK };
