// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:58:24.089Z

const clat_clat_english_Grammar: BankQuestion[] = [
  {
    question: "Which of the following sentences is in the passive voice?",
    options: [
      "The manager reviewed the report.",
      "The team leader wrote the email.",
      "The new policy was implemented yesterday.",
      "The company hired a new employee.",
    ],
    correctAnswer: 2,
    explanation: "The passive voice is a grammatical construction in which the subject of the sentence receives the action described by the verb, rather than performing it. In option c, the subject 'the new policy' receives the action of being implemented, making this sentence an example of the passive voice. On the other hand, options a and b describe actions performed by agents (the manager and the team leader, respectively), whereas in option d, the company is the agent performing the action of hiring. Therefore, only option c is in the passive voice.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { clat_clat_english_Grammar };
