// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:58:58.437Z

const ctet_ctet_child_dev_Child_Psychology: BankQuestion[] = [
  {
    question: "At what age do children typically begin to use symbols to represent objects and concepts?",
    options: [
      "12-18 months",
      "2-3 years",
      "4-5 years",
      "6-7 years",
    ],
    correctAnswer: 1,
    explanation: "Between the ages of 2 and 3, children begin to use symbols such as pictures and objects to represent concepts. This is a significant development in child psychology, as it marks the beginning of symbolic thinking. Children at this stage may start using simple symbols like pictures or gestures to communicate with others. For example, they might point to a picture of a cat to indicate that they want to play with a real cat. As children progress through early childhood, their use of symbols becomes more sophisticated and nuanced, reflecting the growing complexity of their cognitive abilities.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { ctet_ctet_child_dev_Child_Psychology };
