// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_theory_of_computation_Grammar: BankQuestion[] = [
  {
    question: "Which are context free grammars?",
    options: [
      "Regular grammar",
      "Type 2 grammar",
      "Type 3 grammar",
      "Type 0 grammar",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2016",
    sourceDetail: "GATE 2016 Theory of Computation (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_theory_of_computation_Grammar };
