// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.708Z

const gate_cs_operating_systems_Deadlock: BankQuestion[] = [
  {
    question: "Deadlock prevention removes which condition?",
    options: [
      "Mutual exclusion",
      "Circular wait",
      "Hold and wait",
      "All",
    ],
    correctAnswer: 3,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2016",
    sourceDetail: "GATE 2016 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Deadlock };
