// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_network_theory_Kirchhoff: BankQuestion[] = [
  {
    question: "KCL is based on conservation of:",
    options: [
      "Energy",
      "Charge",
      "Power",
      "Voltage",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Network Theory (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_network_theory_Kirchhoff };
