// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_dbms_SQL: BankQuestion[] = [
  {
    question: "Which SQL clause removes duplicate rows?",
    options: [
      "UNIQUE",
      "DISTINCT",
      "PRIMARY",
      "GROUP",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 DBMS (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_dbms_SQL };
