// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_dbms_Normalization: BankQuestion[] = [
  {
    question: "BCNF is stricter version of:",
    options: [
      "1NF",
      "2NF",
      "3NF",
      "4NF",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 DBMS (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_dbms_Normalization };
