// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_computer_networks_Routing: BankQuestion[] = [
  {
    question: "Which algorithm is used in link state routing?",
    options: [
      "Prim",
      "Kruskal",
      "Dijkstra",
      "Bellman Ford",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2022",
    sourceDetail: "GATE 2022 Computer Networks (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_computer_networks_Routing };
