// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_data_structures_Graphs: BankQuestion[] = [
  {
    question: "BFS traversal uses which data structure?",
    options: [
      "Stack",
      "Queue",
      "Heap",
      "Array",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2021",
    sourceDetail: "GATE 2021 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Graphs };
