// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_operating_systems_Memory: BankQuestion[] = [
  {
    question: "Which memory management scheme avoids external fragmentation?",
    options: [
      "Paging",
      "Segmentation",
      "Dynamic partitioning",
      "Contiguous allocation",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2021",
    sourceDetail: "GATE 2021 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Memory };
