// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.705Z

const gate_cs_data_structures_Trees: BankQuestion[] = [
  {
    question: "Height of a balanced BST with n nodes is:",
    options: [
      "O(n)",
      "O(log n)",
      "O(n log n)",
      "O(1)",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2022",
    sourceDetail: "GATE 2022 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Trees };
