// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_signals_and_systems_Fourier: BankQuestion[] = [
  {
    question: "Fourier transform converts signal into:",
    options: [
      "Time domain",
      "Frequency domain",
      "Space domain",
      "Amplitude domain",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Signals and Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_signals_and_systems_Fourier };
