// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_computer_networks_TCP: BankQuestion[] = [
  {
    question: "Which protocol provides reliable communication?",
    options: [
      "UDP",
      "IP",
      "TCP",
      "ICMP",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Computer Networks (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_computer_networks_TCP };
