// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_communication_Modulation: BankQuestion[] = [
  {
    question: "Which modulation has highest bandwidth efficiency?",
    options: [
      "AM",
      "FM",
      "QAM",
      "PCM",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 Communication (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_communication_Modulation };
