// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_control_systems_Stability: BankQuestion[] = [
  {
    question: "Routh Hurwitz criterion determines:",
    options: [
      "Gain",
      "Stability",
      "Phase",
      "Amplitude",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 Control Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_control_systems_Stability };
