// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.708Z

const gate_cs_analog_electronics_Diodes: BankQuestion[] = [
  {
    question: "Zener diode is used for:",
    options: [
      "Amplification",
      "Voltage regulation",
      "Switching",
      "Oscillation",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2018",
    sourceDetail: "GATE 2018 Analog Electronics (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_analog_electronics_Diodes };
