// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_data_structures_Sorting: BankQuestion[] = [
  {
    question: "Average complexity of Merge Sort is:",
    options: [
      "O(n)",
      "O(log n)",
      "O(n log n)",
      "O(n²)",
    ],
    correctAnswer: 2,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2019",
    sourceDetail: "GATE 2019 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  },
  {
    question: "Which sorting algorithms are stable?",
    options: [
      "Merge Sort",
      "Quick Sort",
      "Insertion Sort",
      "Selection Sort",
    ],
    correctAnswer: 0,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Data Structures (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_data_structures_Sorting };
