// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.707Z

const gate_cs_theory_of_computation_Automata: BankQuestion[] = [
  {
    question: "Regular languages are accepted by:",
    options: [
      "PDA",
      "DFA",
      "TM",
      "CFG",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2017",
    sourceDetail: "GATE 2017 Theory of Computation (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_theory_of_computation_Automata };
