// Auto-generated by import-questions.js
// Generated: 2026-05-08T10:10:16.706Z

const gate_cs_operating_systems_Processes: BankQuestion[] = [
  {
    question: "Which scheduling algorithm may cause starvation?",
    options: [
      "Round Robin",
      "Priority Scheduling",
      "FCFS",
      "FIFO",
    ],
    correctAnswer: 1,
    explanation: "Official GATE question - detailed solution available on GATE Overflow",
    difficulty: "hard",
    source: "verified",
    year: "2020",
    sourceDetail: "GATE 2020 Operating Systems (GitHub: shaharyar797/gate-pyq-data)",
  }
];

export { gate_cs_operating_systems_Processes };
