// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:29:39.221Z

const ibps_po_ibps_reasoning_Puzzles: BankQuestion[] = [
  {
    question: "A bat and a ball together cost $1.10. The bat costs $1.00 more than the ball. How much does the ball cost?",
    options: [
      "0.05",
      "0.07",
      "0.08",
      "0.10",
    ],
    correctAnswer: 2,
    explanation: "Step-by-step explanation: Let's denote the cost of the ball as x. Since the bat costs $1.00 more than the ball, the cost of the bat is x + $1.00. The total cost of both items together is $1.10. So, we can set up an equation to represent this: x + (x + $1.00) = $1.10. Simplifying the equation, we get 2x + $1.00 = $1.10. Subtracting $1.00 from both sides gives us 2x = $0.10. Dividing both sides by 2 yields x = $0.05. Therefore, the ball costs $0.05. Option b ($0.07) is a common misconception as it's an average of the cost and the total price. Option c ($0.08) seems plausible but doesn't satisfy the equation. Option d ($0.10) is incorrect because if the bat costs $1.00 more than the ball, it can't be twice the cost of the ball.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { ibps_po_ibps_reasoning_Puzzles };
