// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:28:55.532Z

const jee_advanced_jee_adv_chemistry_Organic_Chemistry: BankQuestion[] = [
  {
    question: "What is the major product of the following reaction?",
    options: [
      "The alkene with the more substituted double bond",
      "A cyclic compound containing a heterocyclic ring and an alkoxy group",
      "An alkyl halide with the halogen atom replaced by an alkyl group",
      "The starting material, cyclohexane, after elimination of water",
    ],
    correctAnswer: 1,
    explanation: "The reaction described is a nucleophilic substitution of the leaving group in 2-methyl-2-butanol with bromide ion. The major product will be formed through the S_N_2 mechanism, where the nucleophile (bromide) attacks the carbon atom bearing the hydroxyl group, resulting in the formation of an alkoxide ion intermediate. This intermediate then undergoes elimination of water to form the final product. Option A is incorrect because the more substituted double bond is not formed during this reaction. Option B is a plausible but incorrect product due to a subsequent rearrangement or elimination step. Option D is also incorrect as it represents a different reaction pathway altogether. The correct answer, option C, reflects the expected major product of this specific nucleophilic substitution reaction.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { jee_advanced_jee_adv_chemistry_Organic_Chemistry };
