// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:56:28.964Z

const jee_main_jee_physics_Mechanics: BankQuestion[] = [
  {
    question: "A particle of mass m is moving in a circular path with velocity v. The radius of the circle is r. What is the minimum speed required for the particle to move in this path?",
    options: [
      "mv^2 / r",
      "(m * v^2) / r",
      "(m * v^2) / (r * m)",
      "0",
    ],
    correctAnswer: 1,
    explanation: "To determine the minimum speed required for the particle to move in a circular path, we can use the concept of centripetal force. The centripetal force is necessary for an object to maintain its circular motion and keep it moving along the curved trajectory. The formula for centripetal force is given by F_c = (m * v^2) / r, where m is the mass of the particle, v is its velocity, and r is the radius of the circle. Therefore, the minimum speed required for the particle to move in this path can be calculated using this formula.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { jee_main_jee_physics_Mechanics };
