// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.263Z

const jee_main_jee_physics_Mechanics: BankQuestion[] = [
  {
    question: "A body of mass 5 kg is moving with a velocity of 10 m/s. The kinetic energy of the body is:",
    options: [
      "250 J",
      "500 J",
      "1000 J",
      "2500 J",
    ],
    correctAnswer: 0,
    explanation: "KE = ½mv² = ½ × 5 × (10)² = ½ × 5 × 100 = 250 J",
    difficulty: "easy",
    source: "verified",
    year: "JEE Main 2024",
    sourceDetail: "Shift 1",
  }
];

export { jee_main_jee_physics_Mechanics };
