// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:30:17.038Z

const nda_nda_maths_Algebra: BankQuestion[] = [
  {
    question: "Solve for x in the equation 2x + 5 = 11",
    options: [
      "First plausible option: x = 3",
      "Second plausible option (common misconception): x = 4, because subtracting 5 from both sides is incorrect",
      "Third plausible option: x = -1/2, using the correct method of subtraction and division",
      "Fourth plausible option: x = √6, assuming a mistake in writing the equation",
    ],
    correctAnswer: 1,
    explanation: "To solve for x, we need to isolate the variable on one side of the equation. We can do this by subtracting 5 from both sides, resulting in 2x = 11 - 5 = 6. Then, we divide both sides by 2 to get x = 6/2 = 3. This is the correct solution. Option b is incorrect because it incorrectly applies the inverse operation of addition (subtracting) instead of subtraction. Option c is correct, but the student may be tempted to make a calculation error when dividing 11 by 2. Option d assumes the original equation was x = √6, which would not result in a valid solution given the initial equation.",
    difficulty: "easy",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { nda_nda_maths_Algebra };
