// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:56:57.891Z

const neet_pg_neet_pg_medicine_Internal_Medicine: BankQuestion[] = [
  {
    question: "A 55-year-old man presents with a 2-month history of progressive dyspnea, orthopnea, and paroxysmal nocturnal dyspnea. Physical examination reveals a loud S4 heart sound. Which of the following is the most likely underlying diagnosis?",
    options: [
      "Coronary artery disease",
      "Cardiomyopathy",
      "Pulmonary hypertension",
      "Heart failure with preserved ejection fraction",
    ],
    correctAnswer: 3,
    explanation: "The patient's symptoms of progressive dyspnea, orthopnea, and paroxysmal nocturnal dyspnea are indicative of heart failure. The loud S4 heart sound is also consistent with left ventricular hypertrophy, which is often seen in patients with preserved ejection fraction (HFpEF). HFpEF is characterized by the inability of the left ventricle to relax properly during diastole, leading to elevated filling pressures and symptoms similar to those experienced by patients with reduced ejection fraction heart failure. The patient's age and presentation are also consistent with HFpEF, which is often seen in older adults. Coronary artery disease (option a) would typically present with chest pain and ECG changes, cardiomyopathy (option b) would present with a wide range of symptoms including arrhythmias, pulmonary hypertension (option c) would present with signs of right heart failure such as jugular venous distension and hepatomegaly, making option d the most likely diagnosis.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { neet_pg_neet_pg_medicine_Internal_Medicine };
