// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.263Z

const neet_ug_neet_chemistry_Environmental_Chemistry: BankQuestion[] = [
  {
    question: "Which of the following is NOT a greenhouse gas?",
    options: [
      "Carbon dioxide",
      "Methane",
      "Nitrogen",
      "Water vapor",
    ],
    correctAnswer: 2,
    explanation: "Nitrogen (N₂) is not a greenhouse gas. It makes up 78% of the atmosphere but does not trap heat. CO₂, CH₄, and H₂O are all greenhouse gases.",
    difficulty: "easy",
    source: "verified",
    year: "NEET 2024",
  }
];

export { neet_ug_neet_chemistry_Environmental_Chemistry };
