// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:58:50.052Z

const rrb_ntpc_rrb_maths_Arithmetic: BankQuestion[] = [
  {
    question: "What is the value of x in the equation: 2x + 5 = 11?",
    options: [
      "2",
      "3",
      "4",
      "5",
    ],
    correctAnswer: 0,
    explanation: "To solve for x, we need to isolate the variable on one side of the equation. First, subtract 5 from both sides: 2x = 11 - 5. This simplifies to 2x = 6. Next, divide both sides by 2 to get rid of the coefficient: x = 6 / 2. Finally, simplify the fraction: x = 3. Therefore, the value of x in the given equation is 3.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { rrb_ntpc_rrb_maths_Arithmetic };
