// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:29:52.711Z

const sbi_po_sbi_reasoning_Puzzles: BankQuestion[] = [
  {
    question: "In a three-room maze, the distance between each room is measured in meters. A person starts at Room A and needs to reach Room C via two intermediate rooms (B and D). The distances AB = 5m, BC = 3m, CD = 4m, DA = 2m, BD = 1m, AD = x m (not given), and DC = y m (also not given). What is the minimum total distance traveled if x + y = 7?",
    options: [
      "5 + 3 + 4 + 2 + 1 = 15 meters",
      "(5+1) + (3+x) + (4+y) = 10 + x + 7 = 17 meters",
      "5 + 1 + (3+x) + 4 + y = 14 + x + y = 21 meters",
      "(5+2) + (3+y) + (4+1) = 7 + 4 + y = 11 + y meters",
    ],
    correctAnswer: 0,
    explanation: "Step-by-step explanation: The problem is asking for the minimum total distance traveled in a three-room maze. To solve this, we need to consider the possible paths and calculate their distances. Option A (15m) represents one of the possible paths from Room A to Room C via two intermediate rooms. We can see that it includes all given distances: AB = 5m, BC = 3m, CD = 4m, DA = 2m, BD = 1m, and AD = x m (and DC = y m). Option B (17 meters) is also a possible path, but it has an extra step. Option C (21 meters) includes the distance AD in addition to the given distances. Option D (11 + y meters) represents another possible path with unknown variable x and y. We know that x + y = 7, so we need to find their values. Since the problem asks for the minimum total distance traveled, we can see that option B has the smallest value because it only includes given distances without any extra steps. Hence, the correct answer is 17 meters.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { sbi_po_sbi_reasoning_Puzzles };
