// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:57:50.287Z

const sbi_po_sbi_quant_Arithmetic: BankQuestion[] = [
  {
    question: "A number is divided by 5 and the quotient is 9. What is the number?",
    options: [
      "45",
      "55",
      "65",
      "75",
    ],
    correctAnswer: 0,
    explanation: "To find the number, we need to multiply the quotient (9) by the divisor (5). This will give us the original number. So, multiplying 9 and 5, we get 45. Therefore, the correct answer is option A, which is 45.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { sbi_po_sbi_quant_Arithmetic };
