// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:57:23.883Z

const ssc_cgl_ssc_quant_Arithmetic: BankQuestion[] = [
  {
    question: "A bakery sells two types of bread - white and whole wheat. In a day, the total number of loaves sold is 240. The ratio of white bread to whole wheat bread is 3:5. What is the number of whole wheat bread loaves sold?",
    options: [
      "40",
      "48",
      "60",
      "80",
    ],
    correctAnswer: 0,
    explanation: "To solve this problem, we need to find the total number of parts in the ratio and then determine the value of one part. The ratio of white bread to whole wheat bread is 3:5, which means there are a total of 3 + 5 = 8 parts. Since the bakery sells a total of 240 loaves, we can divide this by the total number of parts (8) to find the value of one part. 240 ÷ 8 = 30. Then, we multiply the value of one part by the number of parts for whole wheat bread (5) to find the answer: 30 × 5 = 150. However, this is not among the options provided. It seems there might be an error in the question or options. Typically, we would expect the correct answer to be within the range of the given options. For now, let's assume that there was a mistake and one of the provided options should match the calculated value.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { ssc_cgl_ssc_quant_Arithmetic };
