// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.264Z

const ssc_cgl_ssc_quant_Percentage: BankQuestion[] = [
  {
    question: "If 20% of a number is 50, then 50% of that number is:",
    options: [
      "100",
      "125",
      "150",
      "200",
    ],
    correctAnswer: 1,
    explanation: "Let the number be x. 20% of x = 50 → 0.2x = 50 → x = 250. Now 50% of 250 = 0.5 × 250 = 125",
    difficulty: "medium",
    source: "verified",
    year: "SSC CGL 2024",
  }
];

export { ssc_cgl_ssc_quant_Percentage };
