// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:29:36.005Z

const ssc_chsl_ssc_quant_Arithmetic: BankQuestion[] = [
  {
    question: "What is the value of x in the equation 2x + 5 = 11?",
    options: [
      "2",
      "3",
      "4",
      "5",
    ],
    correctAnswer: 3,
    explanation: "To solve this equation, we need to isolate the variable x. First, subtract 5 from both sides of the equation: 2x = 11 - 5. This simplifies to 2x = 6. Next, divide both sides by 2: x = 6/2. Finally, simplify the fraction: x = 3. Therefore, option c (4) is incorrect because it does not satisfy the equation. Option d (5) is also incorrect because it would make the left side of the equation greater than the right side. The correct solution involves subtracting and dividing by a positive number, which eliminates options a (2) and b (3). Therefore, option c is an incorrect answer due to miscalculation, while option d is incorrect as it does not solve the original equation.",
    difficulty: "easy",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { ssc_chsl_ssc_quant_Arithmetic };
