// Auto-generated by import-questions.js
// Generated: 2026-05-07T16:01:44.264Z

const upsc_cse_upsc_history_Modern_India: BankQuestion[] = [
  {
    question: "The Constitution of India was adopted on:",
    options: [
      "26th January 1950",
      "26th November 1949",
      "15th August 1947",
      "26th January 1949",
    ],
    correctAnswer: 1,
    explanation: "The Constitution was adopted by the Constituent Assembly on 26th November 1949 and came into effect on 26th January 1950 (Republic Day).",
    difficulty: "easy",
    source: "verified",
    year: "UPSC CSE 2023",
    sourceDetail: "Prelims Paper 1",
  }
];

export { upsc_cse_upsc_history_Modern_India };
