// Auto-generated by import-questions.js
// Generated: 2026-05-07T18:29:58.334Z

const xat_xat_verbal_Grammar: BankQuestion[] = [
  {
    question: "Identify the correct form of the possessive adjective in the following sentence: 'The student who scored highest ______ his/her performance'.",
    options: [
      "his",
      "his/her",
      "his or her",
      "himself/herself",
    ],
    correctAnswer: 2,
    explanation: "Step-by-step explanation: The possessive adjective 'his' is used to show possession of a singular noun. However, in this sentence, the subject 'the student who scored highest' is a singular noun phrase. To indicate possession of this complex noun phrase, we use the contraction 'his/her', which combines the forms 'his' and 'her'. Option b, 'his/her', is the correct form to use here because it correctly shows possession of the entire sentence. Options a, c, and d are incorrect: option a, 'his', only shows possession of a single noun; options c, 'his or her', is an unnecessary phrase; and option d, 'himself/herself', is used for pronouns, not possessive adjectives. The correct usage of the contraction 'his/her' helps to avoid ambiguity in complex sentences like this one.",
    difficulty: "medium",
    source: "verified",
    year: "AI Generated 2026",
    sourceDetail: "AI-Generated Practice Question (llama3.2)",
  }
];

export { xat_xat_verbal_Grammar };
