// Auto-generated by import-questions.js
// Generated: 2026-05-07T17:58:15.583Z

const xat_xat_quant_Arithmetic: BankQuestion[] = [
  {
    question: "A person bought a car for ₹80,000 and paid 20% of the amount in cash. What is the total amount he needs to pay after discount on the remaining amount?",
    options: [
      "96000",
      "72000",
      "80000",
      "60000",
    ],
    correctAnswer: 0,
    explanation: "To find the total amount he needs to pay, first calculate the amount paid in cash: 20% of ₹80,000 = (20/100) * 80000 = ₹16000. Now subtract this from the original price to get the remaining amount: ₹80,000 - ₹16,000 = ₹64,000. The discount on this remaining amount is not specified, so we cannot calculate the final amount he needs to pay. However, if we assume the discount is 10% of the original price (which is a common assumption in such questions), then the total amount he needs to pay would be: ₹80,000 - 10% of ₹80,000 = ₹80,000 - ₹8,000 = ₹72,000. But since this option is not available, we can assume the discount is 0%, making the final amount ₹80,000.",
    difficulty: "easy",
    source: "verified",
    year: "Local AI Generated 2026",
    sourceDetail: "Ollama llama3.2",
  }
];

export { xat_xat_quant_Arithmetic };
