-- Dynamic Daily Tasks System with AI Personalization Support
-- Created: 2026-07-11
-- Purpose: Replace hardcoded tasks with dynamic, data-driven task generation
-- Future: Support AI-generated personalized study plans

-- ============================================================================
-- Table: user_daily_tasks
-- Stores daily tasks (auto-generated or from personalized plans)
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_daily_tasks (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,

  -- Task definition
  task_type TEXT NOT NULL, -- 'flashcard_review', 'quiz_practice', 'weak_topic', 'mock_test', 'study_guide', 'custom'
  task_data JSONB NOT NULL, -- { label: string, link: string, tag: string, meta: {} }

  -- Status & priority
  status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'skipped'
  priority INTEGER DEFAULT 5, -- 1-10, higher = more important (for sorting)

  -- Source tracking (for future AI plans)
  generated_by TEXT DEFAULT 'auto', -- 'auto', 'ai_personalized', 'manual'
  plan_id INTEGER, -- FK to user_study_plans (future), NULL for auto-generated

  -- Timestamps
  completed_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  -- Prevent duplicate tasks for same day
  UNIQUE(user_id, date, task_type, task_data)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_daily_tasks_lookup ON user_daily_tasks(user_id, date, status);
CREATE INDEX IF NOT EXISTS idx_user_daily_tasks_plan ON user_daily_tasks(plan_id) WHERE plan_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_daily_tasks_type ON user_daily_tasks(task_type, date);

-- ============================================================================
-- Table: user_study_plans (FUTURE - for AI-generated personalized plans)
-- Stores multi-day study plans generated by AI or created manually
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_study_plans (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Plan details
  title TEXT NOT NULL,
  description TEXT,
  goal TEXT NOT NULL, -- 'exam_prep', 'skill_building', 'revision', 'crash_course'

  -- Timeline
  start_date DATE NOT NULL,
  end_date DATE, -- NULL = ongoing

  -- Target & context
  exam_id TEXT, -- which exam this plan targets
  subject_ids TEXT[], -- which subjects to cover
  topics_to_cover TEXT[], -- specific topics to include

  -- AI generation metadata
  ai_generated BOOLEAN DEFAULT FALSE,
  ai_prompt TEXT, -- what user asked for (e.g., "30-day UPSC Polity crash course")
  ai_model TEXT, -- which model generated it

  -- Status
  status TEXT DEFAULT 'active', -- 'draft', 'active', 'completed', 'paused', 'cancelled'

  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Add foreign key constraint to link tasks to plans
ALTER TABLE user_daily_tasks
  DROP CONSTRAINT IF EXISTS fk_plan_id;

ALTER TABLE user_daily_tasks
  ADD CONSTRAINT fk_plan_id
  FOREIGN KEY (plan_id)
  REFERENCES user_study_plans(id)
  ON DELETE SET NULL;

-- Indexes for plans
CREATE INDEX IF NOT EXISTS idx_user_study_plans_user ON user_study_plans(user_id, status);
CREATE INDEX IF NOT EXISTS idx_user_study_plans_dates ON user_study_plans(start_date, end_date);

-- ============================================================================
-- Sample task data structure (JSONB examples)
-- ============================================================================
-- Flashcard review task:
-- {
--   "label": "Review 24 Polity flashcards",
--   "link": "/flashcards",
--   "tag": "Flashcards",
--   "meta": {
--     "deck_id": 1,
--     "cards_due": 24
--   }
-- }

-- Quiz practice task:
-- {
--   "label": "Complete daily quiz goal (10 questions)",
--   "link": "/quiz?exam=upsc&subject=polity",
--   "tag": "Daily Goal",
--   "meta": {
--     "exam_id": "upsc",
--     "subject_id": "polity",
--     "question_count": 10
--   }
-- }

-- Weak topic practice:
-- {
--   "label": "Practice Thermodynamics (52% accuracy)",
--   "link": "/quiz?exam=jee&subject=physics&topic=thermodynamics",
--   "tag": "Weak Topic",
--   "meta": {
--     "topic_id": "thermodynamics",
--     "accuracy": 52
--   }
-- }

-- Mock test:
-- {
--   "label": "Attempt UPSC Prelims Mock #1",
--   "link": "/mock-test?exam=upsc&type=full",
--   "tag": "Mock Test",
--   "meta": {
--     "exam_id": "upsc",
--     "test_type": "full"
--   }
-- }

-- Study guide:
-- {
--   "label": "Read: Fundamental Rights (Article 12–35)",
--   "link": "/learn/polity/fundamental-rights",
--   "tag": "Study Guide",
--   "meta": {
--     "subject_id": "polity",
--     "topic_id": "fundamental-rights"
--   }
-- }

-- ============================================================================
-- Comments for future AI plan generation
-- ============================================================================
-- When generating personalized plans:
-- 1. Create entry in user_study_plans with ai_generated=true
-- 2. Generate daily tasks for each day in the plan's date range
-- 3. Link tasks to plan via plan_id
-- 4. Set generated_by='ai_personalized'
-- 5. Use AI to determine optimal task sequence, difficulty progression
-- 6. Consider user's:
--    - Current level (from mastery data)
--    - Weak areas (from performance)
--    - Time until exam (urgency)
--    - Study habits (from activity data)
