import { Pool } from 'pg';
import { config } from 'dotenv';

config({ path: '.env.local' });

/**
 * Insert high-quality nouns questions generated by Claude Sonnet
 * Topic: nouns-detailed (A1 level)
 * Subtopics: Common vs proper, Singular vs plural, Countable vs uncountable, Gender
 */

const NOUNS_QUESTIONS = [
  // SUBTOPIC 1: Common vs Proper Nouns (15 questions)
  {
    question: "Which word is a proper noun?\n\nProper nouns are names of specific people, places, or things.",
    options: ["Mumbai", "city", "beautiful", "many"],
    correctAnswer: 0,
    explanation: {
      logic: "Proper nouns are names of specific people, places, organizations, or brands. They always start with a capital letter. 'Mumbai' is the name of a specific city in India, so it's a proper noun. Common nouns (city, car, teacher) don't name specific things.",
      trapAlerts: [
        "'city' is a common noun - it refers to any city, not a specific one like Mumbai or Delhi",
        "'beautiful' is an adjective (describing word), not a noun at all",
        "'many' is a quantifier (tells us 'how much'), not a noun"
      ],
      commonMistakes: [
        "Confusing proper nouns with any noun that's important",
        "Forgetting to capitalize proper nouns in writing"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Identify the common noun:\n\nRaj went to the market.",
    options: ["market", "Raj", "went", "the"],
    correctAnswer: 0,
    explanation: {
      logic: "Common nouns name general things, not specific ones. 'Market' refers to any market in general, not a specific named market like 'Big Bazaar'. Common nouns start with lowercase letters (unless at the beginning of a sentence).",
      trapAlerts: [
        "'Raj' is a proper noun - it's a specific person's name and starts with capital R",
        "'went' is a verb (action word), not a noun",
        "'the' is an article (determiner), not a noun"
      ],
      commonMistakes: [
        "Thinking words with 'the' before them are always proper nouns",
        "Confusing verbs and nouns in simple sentences"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Which sentence has ONLY proper nouns?\n\nProper nouns name specific people, places, or brands.",
    options: [
      "Priya lives in Delhi.",
      "The girl lives in the city.",
      "She lives there.",
      "A student lives nearby."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Proper nouns are specific names that start with capital letters. 'Priya' is a person's name, and 'Delhi' is a city's name - both are proper nouns. All other sentences contain common nouns (girl, city, student) or pronouns (she).",
      trapAlerts: [
        "'girl', 'city' are common nouns - they refer to any girl or city, not specific ones",
        "'she' is a pronoun, and 'there' is an adverb - neither are proper nouns",
        "'student' is a common noun - it's not a specific person's name"
      ],
      commonMistakes: [
        "Thinking any noun in a sentence with names becomes a proper noun",
        "Confusing pronouns (she, he, they) with proper nouns"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Choose the sentence with the correct capitalization:",
    options: [
      "My sister studies at Delhi University.",
      "My Sister studies at delhi University.",
      "My sister studies at delhi university.",
      "my sister studies at Delhi University."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Proper nouns (names of specific places, institutions) must be capitalized. 'Delhi University' is the name of a specific institution, so both words start with capitals. 'Sister' is a common noun here, so it stays lowercase (unless it starts the sentence).",
      formula: "Proper noun = Always capitalize | Common noun = lowercase (unless sentence start)",
      trapAlerts: [
        "Option B capitalizes 'Sister' incorrectly - it's a common noun here, not a name",
        "Option C doesn't capitalize 'Delhi University' - institution names are proper nouns",
        "Option D doesn't capitalize 'my' at sentence start - first word always capitalizes"
      ],
      commonMistakes: [
        "Capitalizing common family words (sister, brother, mother) when they're not used as names",
        "Forgetting to capitalize proper nouns like university names, city names"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "In which sentence is 'River' used correctly as a proper noun?",
    options: [
      "The Ganga River flows through many states.",
      "The river is very long.",
      "A river flows near my village.",
      "Rivers are important for farming."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "When 'river' is part of a specific river's name, it becomes part of the proper noun and is capitalized. 'Ganga River' is the name of a specific river. In other sentences, 'river' is just a common noun referring to any river.",
      trapAlerts: [
        "'The river' is common because it doesn't name which specific river",
        "'A river' is common - 'a' indicates any river, not a specific named one",
        "'Rivers' is common plural - referring to rivers in general, not one specific river"
      ],
      commonMistakes: [
        "Not capitalizing river names (writing 'ganga river' instead of 'Ganga River')",
        "Capitalizing 'river' when it's used generally without a specific name"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Complete the sentence with a proper noun:\n\n'I was born in ___.'",
    options: ["India", "a country", "the village", "place"],
    correctAnswer: 0,
    explanation: {
      logic: "Proper nouns name specific places, people, or things. 'India' is the name of a specific country. The other options are common nouns - they refer to types of places but don't name a specific one.",
      trapAlerts: [
        "'a country' is common - the word 'a' shows it's any country, not a specific one",
        "'the village' is common - we don't know which specific village",
        "'place' is common - it's a general word, not the name of a specific location"
      ],
      commonMistakes: [
        "Using articles (a, an, the) with proper nouns of countries (we say 'India', not 'the India')",
        "Forgetting that proper nouns answer 'which specific one?'"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Which word needs to be capitalized?\n\n'my friend arjun goes to oxford school.'",
    options: [
      "All three: My, Arjun, Oxford School",
      "Only arjun",
      "Only oxford",
      "Only my and arjun"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Three capitalizations are needed: (1) 'My' - first word of sentence, (2) 'Arjun' - person's name (proper noun), (3) 'Oxford School' - institution name (proper noun). The first word of every sentence ALWAYS starts with a capital, regardless of whether it's a common or proper noun.",
      trapAlerts: [
        "Capitalizing only 'Arjun' misses 'My' (sentence start) and 'Oxford School' (institution name)",
        "Capitalizing only 'Oxford' is incomplete - 'School' is part of the institution's name",
        "Capitalizing only 'My' and 'Arjun' forgets 'Oxford School' is a proper noun"
      ],
      commonMistakes: [
        "Forgetting the first word of a sentence always needs capitalization",
        "Not capitalizing both words in institution names like 'Oxford School' or 'Delhi University'"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Select the common noun:\n\n'Neha bought a new phone from Reliance Digital.'",
    options: ["phone", "Neha", "Reliance Digital", "new"],
    correctAnswer: 0,
    explanation: {
      logic: "Common nouns are general names for types of things. 'Phone' refers to any mobile phone, not a specific one with a unique name. It's a thing we can count and describe, but it's not the name of a specific item.",
      trapAlerts: [
        "'Neha' is a proper noun - it's the name of a specific person",
        "'Reliance Digital' is a proper noun - it's the name of a specific store brand",
        "'new' is an adjective (describing word) that describes the phone, not a noun"
      ],
      commonMistakes: [
        "Thinking expensive or important items are proper nouns",
        "Confusing adjectives (new, old, big) with nouns"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Why is 'doctor' a common noun but 'Dr. Sharma' a proper noun?",
    options: [
      "Doctor refers to any doctor; Dr. Sharma names a specific person",
      "Doctor is lowercase; Dr. Sharma has a period",
      "Doctor is English; Dr. Sharma is Hindi",
      "Doctor is short; Dr. Sharma is long"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Common nouns refer to general categories or types (any doctor, any teacher). Proper nouns refer to specific individuals or things (this particular doctor named Sharma). The key test: Does it answer 'which one specifically?'",
      trapAlerts: [
        "The period (.) after 'Dr' is just an abbreviation mark, not what makes it proper",
        "Both words are English - language doesn't determine if a noun is common or proper",
        "Length has nothing to do with noun type - 'I' is a proper pronoun but very short"
      ],
      commonMistakes: [
        "Thinking professions (doctor, engineer, teacher) are proper nouns when used with names",
        "Capitalizing job titles when they're used generally (writing 'my friend is a Doctor')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Find the error:\n\n'I visited the taj mahal last Summer.'",
    options: [
      "Both 'Taj Mahal' and 'summer' need fixing",
      "Only 'taj mahal' is wrong",
      "Only 'Summer' is wrong",
      "The sentence is correct"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Two errors: (1) 'Taj Mahal' is a proper noun (monument name) and must be capitalized - 'Taj Mahal', (2) 'summer' is a common noun (season) and should be lowercase - 'summer'. Seasons are NOT proper nouns in English.",
      formula: "Monument/building names = Proper (capitalize) | Seasons = Common (lowercase)",
      trapAlerts: [
        "Fixing only 'Taj Mahal' misses that seasons (summer, winter, spring, autumn) are common nouns",
        "Fixing only 'Summer' misses that 'Taj Mahal' must be capitalized as a monument name",
        "The sentence has two capitalization errors, so it's not correct"
      ],
      commonMistakes: [
        "Capitalizing seasons (Summer, Winter) - they're common nouns in English",
        "Not capitalizing monument names, building names, or famous place names"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Which is a proper noun?\n\n'Amit's dog is a golden retriever.'",
    options: ["Amit", "dog", "golden retriever", "is"],
    correctAnswer: 0,
    explanation: {
      logic: "Only 'Amit' is a proper noun - it's the name of a specific person. 'Golden retriever' might seem like a name, but it's actually a common noun for a breed of dog. Even though it describes a specific type, it's not the name of one particular dog.",
      trapAlerts: [
        "'dog' is a common noun - it refers to any dog, not a specific named dog",
        "'golden retriever' is a breed name (common noun) - like saying 'German Shepherd', it's a type but not a specific dog's name",
        "'is' is a verb (to be), not any type of noun"
      ],
      commonMistakes: [
        "Thinking breed names (German Shepherd, Golden Retriever) are proper nouns - they're common",
        "Capitalizing common nouns because they seem important or specific"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Complete correctly:\n\n'The ___ Himalayas are in ___.'",
    options: [
      "Remove 'The'; add 'India'",
      "Keep 'The'; add 'india'",
      "Remove 'The'; add 'north'",
      "Keep 'The'; add 'a country'"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Mountain range names like 'Himalayas' don't use 'the' in English (we say 'Himalayas', not 'the Himalayas'). Country names like 'India' are proper nouns and must be capitalized. Note: This is different from river names, which DO use 'the' (the Ganga).",
      formula: "Mountain ranges = No 'the' | Rivers = Use 'the' | Countries = Capitalize",
      trapAlerts: [
        "Option B keeps 'the' incorrectly and doesn't capitalize 'India'",
        "Option C removes 'the' correctly but uses 'north' (common noun) instead of the country name",
        "Option D keeps 'the' and uses 'a country' (common noun) instead of the specific name"
      ],
      commonMistakes: [
        "Adding 'the' before mountain ranges (the Himalayas) - correct is just 'Himalayas'",
        "Not capitalizing country names in English"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Which sentence uses 'mother' as a proper noun?",
    options: [
      "I asked Mother to help me.",
      "My mother is a teacher.",
      "The mother loves her child.",
      "Every mother is special."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "When family words (Mother, Father, Uncle) are used AS names (instead of 'my mother', 'his father'), they become proper nouns and are capitalized. 'I asked Mother' uses it as her name. 'My mother' uses it as a common noun with a possessive.",
      formula: "Family word used AS name = Proper (capitalize) | With my/his/her = Common (lowercase)",
      trapAlerts: [
        "'my mother' has 'my' before it, making it a common noun, not a name",
        "'the mother' uses 'the', making it common - it refers to any mother",
        "'every mother' refers to all mothers in general - common noun"
      ],
      commonMistakes: [
        "Always capitalizing Mother, Father, etc. - only capitalize when used AS the name",
        "Writing 'My Mother' instead of 'my mother' when 'my' is used"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "What type of noun is 'school' in this sentence?\n\n'Priya goes to school every day.'",
    options: [
      "Common noun",
      "Proper noun",
      "Both common and proper",
      "Neither - it's a verb"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "'School' here is a common noun because it refers to any school in general, not a specific school's name like 'Delhi Public School'. When we say 'go to school', we mean the general activity of attending educational institutions.",
      trapAlerts: [
        "'school' is not proper because we don't know which specific school - no name is given",
        "It can't be both - in this sentence it's clearly common (general reference)",
        "'school' is definitely a noun (a place), not a verb (action word)"
      ],
      commonMistakes: [
        "Thinking 'school' is always proper because it's an institution",
        "Capitalizing 'school' when it's used generally (write 'I go to school', not 'School')"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Choose the sentence with all nouns correctly capitalized:",
    options: [
      "Raj and Sanya visited the Red Fort in Delhi on Tuesday.",
      "Raj and Sanya visited the red fort in Delhi on tuesday.",
      "raj and sanya visited the Red Fort in delhi on Tuesday.",
      "Raj and sanya visited the Red fort in Delhi on Tuesday."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "Proper nouns that need capitals: 'Raj' and 'Sanya' (names), 'Red Fort' (monument name), 'Delhi' (city name), 'Tuesday' (day name). All specific names of people, places, days, and monuments are proper nouns in English.",
      formula: "Names + Places + Days + Monuments = All capitalize (Proper nouns)",
      trapAlerts: [
        "Option B doesn't capitalize 'Red Fort' (monument) and 'Tuesday' (day) - both proper",
        "Option C doesn't capitalize 'Raj', 'Sanya', and 'Delhi' - all are proper nouns",
        "Option D doesn't capitalize 'Sanya' (name) and only capitalizes 'Red' in 'Red Fort'"
      ],
      commonMistakes: [
        "Not capitalizing days of the week - they're proper nouns in English",
        "Capitalizing only the first word in monument names (writing 'Red fort' instead of 'Red Fort')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },

  // SUBTOPIC 2: Singular vs Plural (15 questions)
  {
    question: "What is the plural of 'book'?",
    options: ["books", "bookes", "book", "bookies"],
    correctAnswer: 0,
    explanation: {
      logic: "For most regular nouns, we form the plural by adding '-s' to the singular form. 'Book' becomes 'books'. This is the most common pluralization rule in English.",
      formula: "Regular noun + s = Plural (book → books, pen → pens, car → cars)",
      trapAlerts: [
        "'bookes' adds '-es' incorrectly - we only add '-es' to nouns ending in s, x, z, ch, sh",
        "'book' is singular, not plural - it refers to only one book",
        "'bookies' is not a real plural form - it sounds like 'cookies' but that's a different pattern"
      ],
      commonMistakes: [
        "Adding '-es' to all nouns - only needed for words ending in s, x, z, ch, sh",
        "Forgetting to add anything to make plural (using 'book' for both singular and plural)"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Choose the correct plural form:\n\n'Two ___ are flying in the sky.'",
    options: ["birds", "bird", "birdes", "birdies"],
    correctAnswer: 0,
    explanation: {
      logic: "'Two' tells us we need plural form. 'Bird' is a regular noun, so we add '-s' to make 'birds'. Numbers like two, three, four always need plural nouns after them (except for 'one').",
      formula: "Number (2+) + plural noun | one + singular noun",
      trapAlerts: [
        "'bird' is singular - can't use it after 'two' (we say 'two birds', not 'two bird')",
        "'birdes' adds '-es' unnecessarily - 'bird' doesn't end in s, x, z, ch, or sh",
        "'birdies' is informal/baby talk, not the standard plural form"
      ],
      commonMistakes: [
        "Using singular after numbers greater than one (saying 'two bird' instead of 'two birds')",
        "Direct translation from Hindi where plural markers work differently"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "What is the plural of 'box'?",
    options: ["boxes", "boxs", "boxies", "box"],
    correctAnswer: 0,
    explanation: {
      logic: "Nouns ending in s, x, z, ch, or sh need '-es' (not just '-s') to form plural. 'Box' ends in 'x', so we add '-es' to make 'boxes'. The '-es' ending adds an extra syllable: box (1 syllable) → box-es (2 syllables).",
      formula: "Noun ending in s/x/z/ch/sh + es = Plural (box → boxes, bus → buses, dish → dishes)",
      trapAlerts: [
        "'boxs' just adds '-s' - wrong for words ending in x (too hard to pronounce 'boxs')",
        "'boxies' is not a valid plural pattern in English",
        "'box' is singular - unchanged, refers to only one box"
      ],
      commonMistakes: [
        "Adding only '-s' to words ending in x, s, z, ch, sh (writing 'boxs', 'buss')",
        "Not recognizing the pronunciation difficulty that '-es' solves"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Find the error:\n\n'I have three pencils and two boxs.'",
    options: [
      "'boxs' should be 'boxes'",
      "'pencils' should be 'pencil'",
      "'have' should be 'has'",
      "The sentence is correct"
    ],
    correctAnswer: 0,
    explanation: {
      logic: "The error is 'boxs'. Since 'box' ends in 'x', we must add '-es' (not just '-s') to form the plural: 'boxes'. 'Pencils' is correct because 'pencil' doesn't end in s/x/z/ch/sh, so regular '-s' is fine.",
      formula: "Noun ending in x + es = boxes (not boxs)",
      trapAlerts: [
        "'pencils' is correct - 'pencil' is regular and just needs '-s' for plural",
        "'have' is correct - we use 'have' with 'I' (not 'has', which goes with he/she/it)",
        "The sentence has one error ('boxs'), so it's not correct"
      ],
      commonMistakes: [
        "Forgetting the -es rule for nouns ending in s, x, z, ch, sh",
        "Thinking all plurals just add '-s' regardless of the ending"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "What is the plural of 'child'?",
    options: ["children", "childs", "childes", "childrens"],
    correctAnswer: 0,
    explanation: {
      logic: "'Child' is an irregular noun. It doesn't follow the regular '-s' or '-es' rules. Instead, it changes to 'children'. Irregular plurals must be memorized - there's no rule to predict them.",
      formula: "Irregular plurals: child → children, man → men, woman → women, tooth → teeth, foot → feet",
      trapAlerts: [
        "'childs' applies regular '-s' rule, but 'child' is irregular",
        "'childes' tries '-es' rule, but 'child' is irregular",
        "'childrens' adds '-s' to 'children', creating double plural (wrong!)"
      ],
      commonMistakes: [
        "Treating all nouns as regular and adding '-s' (writing 'childs', 'mans', 'foots')",
        "Adding '-s' to irregular plurals that are already plural (writing 'childrens', 'mens')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Choose the correct sentence:",
    options: [
      "The children are playing.",
      "The childs are playing.",
      "The childrens are playing.",
      "The children is playing."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "'Children' is the irregular plural of 'child'. With plural subjects, we use 'are' (not 'is'). 'Children' is already plural, so we don't add another '-s'.",
      formula: "Plural subject + are | Singular subject + is",
      trapAlerts: [
        "'childs' is wrong - 'child' has irregular plural 'children', not regular 'childs'",
        "'childrens' adds '-s' to 'children' - double plural error, 'children' is already plural",
        "'children is' has wrong verb - plural 'children' needs 'are', not 'is'"
      ],
      commonMistakes: [
        "Using 'childs' instead of irregular 'children'",
        "Adding '-s' to irregular plurals (writing 'childrens', 'mens', 'womens')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "What is the plural of 'class'?",
    options: ["classes", "class", "classs", "classies"],
    correctAnswer: 0,
    explanation: {
      logic: "'Class' ends in '-ss' (double s), which is like an 's' ending. For nouns ending in s, x, z, ch, sh, we add '-es': class → classes. This adds a syllable for easier pronunciation.",
      formula: "Noun ending in ss + es = Plural (class → classes, glass → glasses)",
      trapAlerts: [
        "'class' unchanged is singular - refers to one class only",
        "'classs' just adds 's' - creates 'three s letters' which is hard to say and wrong",
        "'classies' is not a standard plural pattern in English"
      ],
      commonMistakes: [
        "Adding only '-s' to words ending in 's' (writing 'classs')",
        "Not recognizing double 's' needs '-es' treatment"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Find the correctly formed plural:\n\n'city'",
    options: ["cities", "citys", "cityes", "city"],
    correctAnswer: 0,
    explanation: {
      logic: "Nouns ending in consonant + 'y' change 'y' to 'i' and add '-es': city → cities. This rule applies to words like party → parties, baby → babies, family → families. Note: If there's a vowel before 'y', just add '-s' (boy → boys).",
      formula: "Consonant + y → change y to i + es (city → cities) | Vowel + y → just add s (boy → boys)",
      trapAlerts: [
        "'citys' just adds '-s' without changing 'y' to 'i' - wrong for consonant + y pattern",
        "'cityes' keeps 'y' and adds '-es' - we must change 'y' to 'i' first",
        "'city' unchanged is singular - only one city"
      ],
      commonMistakes: [
        "Adding '-s' without changing 'y' to 'i' (writing 'citys', 'babys')",
        "Confusing consonant + y (cities) with vowel + y (boys) patterns"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "What is the plural of 'knife'?",
    options: ["knives", "knifes", "knifs", "knife"],
    correctAnswer: 0,
    explanation: {
      logic: "Nouns ending in 'f' or 'fe' usually change to 'ves' for plural: knife → knives, leaf → leaves, wife → wives, life → lives. The 'f' sound changes to 'v' sound in plural.",
      formula: "Noun ending in f/fe → ves (knife → knives, leaf → leaves, wolf → wolves)",
      trapAlerts: [
        "'knifes' just adds '-s' - wrong for words ending in 'f/fe' (should change to 'ves')",
        "'knifs' drops 'e' and adds 's' - not a real plural pattern",
        "'knife' unchanged is singular - only one knife"
      ],
      commonMistakes: [
        "Adding '-s' to words ending in f/fe without changing to 'ves'",
        "Not noticing the 'f' to 'v' sound change in plural"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Which sentence is correct?",
    options: [
      "I have two feet.",
      "I have two foots.",
      "I have two feets.",
      "I have two foot."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "'Foot' is an irregular noun. Its plural is 'feet' (not 'foots'). Other body parts with similar patterns: tooth → teeth, goose → geese. This vowel change (oo → ee) is an old English pattern for plurals.",
      formula: "Irregular plurals (vowel change): foot → feet, tooth → teeth, goose → geese",
      trapAlerts: [
        "'foots' treats 'foot' as regular - wrong, it's irregular with vowel change",
        "'feets' adds '-s' to 'feet' - double plural error, 'feet' is already plural",
        "'foot' is singular - can't use with 'two' (needs plural after numbers > 1)"
      ],
      commonMistakes: [
        "Treating irregular nouns as regular (writing 'foots', 'tooths', 'mans')",
        "Adding '-s' to irregular plurals (writing 'feets', 'teeths', 'mens')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Complete the sentence:\n\n'There are many ___ in the pond.'",
    options: ["fish", "fishes", "fishs", "fishies"],
    correctAnswer: 0,
    explanation: {
      logic: "'Fish' is special - it stays the same in both singular and plural. We say 'one fish' and 'many fish' (not 'fishes'). Other nouns like this: sheep → sheep, deer → deer. Note: 'Fishes' exists but means 'different species of fish'.",
      formula: "Same singular and plural: fish → fish, sheep → sheep, deer → deer",
      trapAlerts: [
        "'fishes' can mean different species, but for general plural 'fish' is correct",
        "'fishs' adds '-s' incorrectly - 'fish' doesn't follow regular rules",
        "'fishies' is baby talk/informal, not standard English plural"
      ],
      commonMistakes: [
        "Adding '-s' to 'fish' for general plural (writing 'many fishs')",
        "Not knowing nouns with same singular/plural form exist"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "What is the plural of 'tomato'?",
    options: ["tomatoes", "tomatos", "tomatoe", "tomato"],
    correctAnswer: 0,
    explanation: {
      logic: "Nouns ending in 'o' preceded by a consonant usually add '-es' for plural: tomato → tomatoes, potato → potatoes, hero → heroes. Note: If there's a vowel before 'o', just add '-s' (radio → radios, zoo → zoos).",
      formula: "Consonant + o + es = Plural (tomato → tomatoes, potato → potatoes)",
      trapAlerts: [
        "'tomatos' just adds '-s' - missing the required '-es' for consonant + o words",
        "'tomatoe' adds 'e' without 's' - not plural (and 'tomatoe' isn't even a word)",
        "'tomato' unchanged is singular - only one tomato"
      ],
      commonMistakes: [
        "Adding only '-s' to consonant + o words (writing 'tomatos', 'potatos')",
        "Confusing consonant + o (tomatoes) with vowel + o (radios) patterns"
      ]
    },
    difficulty: "hard",
    level: "A1"
  },
  {
    question: "Find the sentence with the correct plural usage:",
    options: [
      "Three boys are playing in the park.",
      "Three boy are playing in the park.",
      "Three boys is playing in the park.",
      "Three boies are playing in the park."
    ],
    correctAnswer: 0,
    explanation: {
      logic: "'Boy' ends in vowel + 'y', so we just add '-s': boys (not 'boies'). With plural subjects, we use 'are' (not 'is'). Numbers greater than one always need plural nouns.",
      formula: "Vowel + y + s = boys | Consonant + y → ies = babies",
      trapAlerts: [
        "'boy' is singular - can't use with 'three' (number > 1 needs plural)",
        "'boys is' has wrong verb - plural subject needs 'are', not 'is'",
        "'boies' incorrectly changes 'y' to 'ie' - only do this when consonant comes before 'y'"
      ],
      commonMistakes: [
        "Using singular noun after numbers > 1 (saying 'three boy')",
        "Changing vowel + y to 'ies' unnecessarily (writing 'boies' instead of 'boys')"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },
  {
    question: "Which noun has an irregular plural?",
    options: ["man", "cat", "house", "tree"],
    correctAnswer: 0,
    explanation: {
      logic: "'Man' is irregular - its plural is 'men' (not 'mans'). It changes the vowel 'a' to 'e'. The other nouns are regular: cat → cats, house → houses, tree → trees. Regular plurals just add '-s' or '-es'.",
      formula: "Irregular: man → men | Regular: cat → cats, house → houses",
      trapAlerts: [
        "'cat' is regular - just add '-s' to make 'cats'",
        "'house' is regular - add '-s' to make 'houses' (even though it ends in 'e', still add 's')",
        "'tree' is regular - just add '-s' to make 'trees'"
      ],
      commonMistakes: [
        "Treating irregular nouns as regular (writing 'mans' instead of 'men')",
        "Not memorizing common irregular plurals (man/men, woman/women, child/children)"
      ]
    },
    difficulty: "easy",
    level: "A1"
  },
  {
    question: "Complete correctly:\n\n'The ___ of the book are torn.'",
    options: ["pages", "page", "pagees", "page's"],
    correctAnswer: 0,
    explanation: {
      logic: "'The' at the start and 'are' (plural verb) tell us we need plural form. 'Page' is a regular noun, so add '-s': pages. The sentence means multiple pages are torn, not just one.",
      formula: "Plural subject + are | Singular subject + is",
      trapAlerts: [
        "'page' is singular - doesn't match with 'are' (singular needs 'is')",
        "'pagees' adds '-es' unnecessarily - 'page' doesn't end in s/x/z/ch/sh",
        "'page's' is possessive (page's corner), not plural"
      ],
      commonMistakes: [
        "Confusing possessive ('s) with plural ('s without apostrophe)",
        "Using singular noun with plural verb 'are'"
      ]
    },
    difficulty: "medium",
    level: "A1"
  },

  // SUBTOPIC 3: Countable vs Uncountable (15 questions)
  // Continuing in next batch...
];

async function insertQuestions() {
  const pool = new Pool({
    connectionString: process.env.POSTGRES_URL,
    ssl: { rejectUnauthorized: false },
  });

  try {
    console.log('🎓 Inserting Nouns Questions (Batch 1/4)');
    console.log('='.repeat(80));
    console.log(`\n📋 Topic: nouns-detailed (A1 level)`);
    console.log(`   Questions in this batch: ${NOUNS_QUESTIONS.length}`);
    console.log(`   Subtopics covered: Common vs Proper (15), Singular vs Plural (15)\n`);

    let inserted = 0;
    for (const q of NOUNS_QUESTIONS) {
      await pool.query(
        `INSERT INTO english_questions
         (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())`,
        [
          'foundation',
          'nouns-detailed',
          q.level,
          q.question,
          JSON.stringify(q.options),
          q.correctAnswer,
          JSON.stringify(q.explanation),
          q.difficulty,
        ]
      );
      inserted++;

      if (inserted % 10 === 0) {
        console.log(`   ✓ Inserted ${inserted}/${NOUNS_QUESTIONS.length}...`);
      }
    }

    console.log(`\n✅ Successfully inserted ${inserted} questions!`);
    console.log(`\n📊 Progress: ${inserted}/60 questions for nouns-detailed`);
    console.log(`   Next batch will add 30 more (Countable/Uncountable + Practice)`);

  } catch (error: any) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

insertQuestions();
