-- Restore Sample English Questions
-- Run this in Supabase SQL Editor to get started

-- First, verify table is empty
SELECT COUNT(*) as current_count FROM english_questions;

-- Insert 40 high-quality sample questions for Parts of Speech
-- path_id = 'foundation', topic_id = 'parts-of-speech', level = 'beginner'

-- NOUNS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is a common noun in the sentence: "The teacher gave Sarah a book"?', '["teacher", "Sarah", "gave", "The"]', 0, 'A common noun names a general person, place, or thing. "Teacher" is a common noun because it refers to any teacher in general, not a specific person. "Sarah" is a proper noun (specific person), "gave" is a verb, and "The" is an article.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the abstract noun in: "Her kindness touched everyone in the room."', '["Her", "kindness", "everyone", "room"]', 1, 'An abstract noun represents an idea, quality, or state rather than a concrete object. "Kindness" is an abstract noun representing the quality of being kind. "Her" is a pronoun, "everyone" is a pronoun, and "room" is a concrete noun.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence contains a collective noun?', '["The dog barked loudly.", "A flock of birds flew overhead.", "She reads books daily.", "He drives carefully."]', 1, 'A collective noun refers to a group of people, animals, or things treated as a single unit. "Flock" is a collective noun referring to a group of birds. The other sentences contain only individual nouns.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What type of noun is "happiness" in: "Happiness is a choice"?', '["proper noun", "abstract noun", "concrete noun", "collective noun"]', 1, 'An abstract noun names something that cannot be physically touched or seen. "Happiness" is an abstract noun representing an emotion or state of being. It cannot be touched, seen, or measured physically.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'In "The United Nations met yesterday," what type of noun is "United Nations"?', '["common noun", "proper noun", "abstract noun", "compound noun"]', 1, 'A proper noun names a specific person, place, organization, or thing and is always capitalized. "United Nations" is a proper noun because it names a specific international organization. Even though it consists of multiple words, it functions as a single proper noun.', 'hard');

-- PRONOUNS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is a personal pronoun in: "She gave him the book"?', '["She", "gave", "the", "book"]', 0, 'A personal pronoun replaces a noun and refers to specific people or things. "She" is a personal pronoun (third person singular feminine). "Him" is also a personal pronoun, but the question asks for one answer. "Gave" is a verb, "the" is an article, and "book" is a noun.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the reflexive pronoun: "He prepared himself for the exam."', '["He", "prepared", "himself", "exam"]', 2, 'A reflexive pronoun ends in -self or -selves and refers back to the subject of the sentence. "Himself" is reflexive because it refers back to "He" (the subject). "He" is a personal pronoun, "prepared" is a verb, and "exam" is a noun.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence uses a possessive pronoun correctly?', '["The book is her.", "The book is hers.", "The book is she.", "The book is her book."]', 1, 'A possessive pronoun shows ownership without being followed by a noun. "Hers" is a possessive pronoun that stands alone. "Her" is a possessive adjective (must be followed by a noun), "she" is a subject pronoun, and "her book" uses a possessive adjective, not pronoun.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What type of pronoun is "who" in: "Who is coming to the party?"', '["personal", "interrogative", "relative", "demonstrative"]', 1, 'An interrogative pronoun is used to ask questions. "Who" is interrogative because it asks a question about which person. Relative pronouns connect clauses, demonstrative pronouns point to things, and personal pronouns replace nouns.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the demonstrative pronoun: "That is exactly what I meant."', '["That", "exactly", "what", "I"]', 0, 'A demonstrative pronoun points to specific things (this, that, these, those). "That" is demonstrative here, pointing to something specific. "What" is an interrogative/relative pronoun, "I" is a personal pronoun, and "exactly" is an adverb.', 'medium');

-- VERBS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is the main verb in: "She has been studying for three hours"?', '["has", "been", "studying", "hours"]', 2, 'In a verb phrase, the main verb carries the primary meaning. "Studying" is the main verb (present participle of "study"). "Has" and "been" are auxiliary (helping) verbs. "Hours" is a noun.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the transitive verb: "The chef cooked a delicious meal."', '["chef", "cooked", "delicious", "meal"]', 1, 'A transitive verb requires a direct object to complete its meaning. "Cooked" is transitive because it has a direct object "meal" (what was cooked). "Chef" and "meal" are nouns, "delicious" is an adjective.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence contains a linking verb?', '["He runs every morning.", "She seems tired today.", "They ate dinner early.", "We finished the project."]', 1, 'A linking verb connects the subject to a description rather than showing action. "Seems" is a linking verb connecting "she" to "tired" (her state). "Runs," "ate," and "finished" are action verbs.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What is the tense of the verb in: "By next year, I will have graduated"?', '["simple future", "future perfect", "present perfect", "future progressive"]', 1, 'Future perfect tense shows an action that will be completed before a specific time in the future. "Will have graduated" is future perfect (will have + past participle). It indicates completion before "next year."', 'hard'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the auxiliary verb: "She can speak three languages fluently."', '["She", "can", "speak", "languages"]', 1, 'An auxiliary (helping) verb combines with a main verb to show tense, mood, or voice. "Can" is a modal auxiliary showing ability. "Speak" is the main verb. "She" is a pronoun, "languages" is a noun.', 'easy');

-- ADJECTIVES - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is an adjective in: "The beautiful garden blooms brightly"?', '["The", "beautiful", "garden", "brightly"]', 1, 'An adjective modifies (describes) a noun or pronoun. "Beautiful" is an adjective describing "garden" (what kind of garden). "The" is an article, "garden" is a noun, "brightly" is an adverb.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the superlative adjective: "She is the smartest student in the class."', '["She", "smartest", "student", "class"]', 1, 'A superlative adjective compares three or more items, showing the highest or lowest degree. "Smartest" is superlative (most smart among all students). Comparative would be "smarter" (two items), positive is "smart."', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence uses a demonstrative adjective?', '["This book is interesting.", "The book is interesting.", "My book is interesting.", "Any book is interesting."]', 0, 'A demonstrative adjective points to a specific noun (this, that, these, those). "This" specifies which book. "The" is an article, "my" is a possessive adjective, "any" is an indefinite adjective.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What type of adjective is "five" in: "She bought five apples"?', '["descriptive", "quantitative", "possessive", "interrogative"]', 1, 'A quantitative adjective indicates quantity or number. "Five" is quantitative because it tells how many apples. Descriptive adjectives describe qualities (red, sweet), possessive show ownership (her, my).', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the proper adjective: "She loves Italian cuisine."', '["She", "loves", "Italian", "cuisine"]', 2, 'A proper adjective is derived from a proper noun and is capitalized. "Italian" is a proper adjective derived from "Italy" (proper noun), describing the type of cuisine. "She" is a pronoun, "loves" is a verb, "cuisine" is a common noun.', 'hard');

-- ADVERBS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is an adverb in: "She sings beautifully every day"?', '["She", "sings", "beautifully", "day"]', 2, 'An adverb modifies a verb, adjective, or another adverb. "Beautifully" is an adverb modifying "sings" (how she sings). Many adverbs end in -ly. "She" is a pronoun, "sings" is a verb, "day" is a noun.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the adverb of frequency: "He always arrives on time."', '["He", "always", "arrives", "time"]', 1, 'Adverbs of frequency tell how often something happens (always, never, often, rarely, sometimes). "Always" indicates that he arrives on time every single time. "He" is a pronoun, "arrives" is a verb, "time" is a noun.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which adverb modifies another adverb in: "She runs very quickly"?', '["She", "runs", "very", "quickly"]', 2, 'An adverb can modify another adverb to show degree or intensity. "Very" modifies "quickly" (how quickly). "Quickly" modifies "runs" (how she runs). "She" is a pronoun, "runs" is a verb.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What does the adverb modify in: "The extremely tall building"?', '["noun", "verb", "adjective", "adverb"]', 2, 'In this phrase, "extremely" modifies "tall" (an adjective), showing the degree of tallness. Adverbs can modify verbs, adjectives, or other adverbs. Here it intensifies the adjective "tall."', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the adverb of place: "Please come here immediately."', '["Please", "come", "here", "immediately"]', 2, 'Adverbs of place tell where something happens (here, there, everywhere, nowhere, outside). "Here" indicates where to come. "Immediately" is an adverb of time. "Please" is an interjection/adverb of manner, "come" is a verb.', 'hard');

-- PREPOSITIONS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is a preposition in: "The book is on the table"?', '["book", "is", "on", "table"]', 2, 'A preposition shows the relationship between a noun/pronoun and other words. "On" is a preposition showing the spatial relationship between "book" and "table." "Book" and "table" are nouns, "is" is a verb.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the prepositional phrase: "She walked through the garden quietly."', '["She walked", "walked through", "through the garden", "garden quietly"]', 2, 'A prepositional phrase consists of a preposition + its object (+ any modifiers). "Through the garden" is the complete prepositional phrase: preposition "through" + object "garden" with article "the."', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Which preposition shows time: "We will meet _____ Friday"?', '["at", "on", "in", "by"]', 1, 'Prepositions of time follow specific patterns. "On" is used with days of the week (on Friday, on Monday). "At" is for specific times (at 5 PM), "in" for months/years/seasons (in June), "by" for deadlines.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What is the object of the preposition in: "He jumped over the fence"?', '["He", "jumped", "over", "fence"]', 3, 'The object of a preposition is the noun or pronoun that follows it. "Fence" is the object of the preposition "over" (what was jumped over). "He" is the subject, "jumped" is the verb, "over" is the preposition.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence uses a complex preposition (phrase)?', '["She sat beside me.", "He arrived after lunch.", "They succeeded in spite of difficulties.", "We walked toward the station."]', 2, 'A complex preposition consists of multiple words functioning as a single preposition. "In spite of" is a three-word complex preposition meaning "despite." The other options use single-word prepositions.', 'hard');

-- CONJUNCTIONS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is a coordinating conjunction: "She is tired but happy"?', '["She", "is", "but", "happy"]', 2, 'Coordinating conjunctions connect words, phrases, or clauses of equal importance (FANBOYS: for, and, nor, but, or, yet, so). "But" connects two adjectives showing contrast. "She" is a pronoun, "is" is a verb, "happy" is an adjective.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the subordinating conjunction: "Although it rained, we went hiking."', '["Although", "it", "rained", "went"]', 0, 'A subordinating conjunction introduces a dependent clause and shows its relationship to the main clause. "Although" introduces "it rained" and shows contrast. Common ones include: because, since, although, if, when, while.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'Which conjunction pair is correlative: "_____ John _____ Mary attended"?', '["and ... and", "either ... or", "but ... and", "if ... then"]', 1, 'Correlative conjunctions work in pairs to connect equivalent elements. "Either ... or" is correlative. Other pairs include: neither...nor, not only...but also, both...and. They must be used together.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What type of conjunction is "because" in: "He stayed home because he was sick"?', '["coordinating", "subordinating", "correlative", "conjunctive adverb"]', 1, 'Subordinating conjunctions connect dependent clauses to independent clauses. "Because" introduces "he was sick" (dependent clause) and connects it to "He stayed home" (independent clause). It shows cause-effect relationship.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the conjunctive adverb: "She studied hard; therefore, she passed."', '["studied", "hard", "therefore", "passed"]', 2, 'Conjunctive adverbs connect independent clauses and show their relationship (however, therefore, moreover, nevertheless). "Therefore" shows cause-effect and requires a semicolon before it. "Studied" and "passed" are verbs, "hard" is an adverb.', 'hard');

-- INTERJECTIONS - 5 questions
INSERT INTO english_questions (path_id, topic_id, level, question, options, correct_answer, explanation, difficulty) VALUES
('foundation', 'parts-of-speech', 'beginner', 'Which word is an interjection: "Wow! That was amazing!"?', '["Wow", "That", "was", "amazing"]', 0, 'An interjection expresses strong emotion or sudden feeling and is usually followed by an exclamation mark. "Wow" is an interjection showing surprise or admiration. "That" is a pronoun, "was" is a verb, "amazing" is an adjective.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Identify the interjection expressing disappointment: "_____, I missed the bus."', '["Alas", "Hooray", "Yay", "Bravo"]', 0, 'Different interjections express different emotions. "Alas" expresses disappointment, regret, or sorrow. "Hooray," "Yay," and "Bravo" express joy, excitement, or approval.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which interjection shows hesitation or pause in: "Well, I am not sure about that"?', '["Well", "I", "not", "sure"]', 0, 'Some interjections like "well," "um," "uh" show hesitation, thinking, or transition. "Well" here shows the speaker is pausing to think before responding. It softens the disagreement. "I" is a pronoun, "not" is an adverb, "sure" is an adjective.', 'medium'),
('foundation', 'parts-of-speech', 'beginner', 'What type of word is "Ouch" in: "Ouch! That hurt!"?', '["noun", "verb", "adjective", "interjection"]', 3, 'An interjection expresses sudden emotion without grammatical connection to the sentence. "Ouch" expresses sudden pain. Interjections stand alone and don''t modify other words. "Hurt" is a verb.', 'easy'),
('foundation', 'parts-of-speech', 'beginner', 'Which sentence uses an interjection correctly?', '["She said hooray quietly.", "Hooray! We won the game!", "The hooray was loud.", "He hooray at the news."]', 1, 'Interjections are standalone expressions of emotion, typically followed by an exclamation mark. "Hooray! We won the game!" correctly uses "hooray" as an interjection showing excitement. The other options misuse it as a noun, verb, or adverb.', 'medium');

-- Verify insertion
SELECT
  COUNT(*) as total_questions,
  COUNT(CASE WHEN difficulty = 'easy' THEN 1 END) as easy,
  COUNT(CASE WHEN difficulty = 'medium' THEN 1 END) as medium,
  COUNT(CASE WHEN difficulty = 'hard' THEN 1 END) as hard
FROM english_questions
WHERE path_id = 'foundation' AND topic_id = 'parts-of-speech';
